rtai-py not installed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25047,9 +25047,9 @@ CONFIG_RTAI_PYTHON=y
 if test -d $srcdir/rtai-py; then
    ac_config_files="$ac_config_files rtai-py/GNUmakefile"
 
-elif test \! x$CONFIG_RTAI_TESTSUITE = x; then
-     { { echo "$as_me:$LINENO: error: testsuite package is missing" >&5
-echo "$as_me: error: testsuite package is missing" >&2;}
+elif test \! x$CONFIG_RTAI_PYTHON = x; then
+     { { echo "$as_me:$LINENO: error: python package is missing" >&5
+echo "$as_me: error: python package is missing" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
