Make the global heap size configurable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1075,6 +1075,7 @@ Optional Features:
  --enable-fpu		Enable FPU support
  --enable-math-c99	Enable math C99 support
  --enable-malloc-vmalloc	Enable vmalloc support in malloc
+ --enable-malloc-heap-size	Set size of real-time malloc heap
  --enable-cpus		Enable CPUs
  --enable-dox-doc	Build Doxygen documentation
 --enable-dbx	Build Docbook XML documentation.
@@ -5180,7 +5181,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5183 "configure"' > conftest.$ac_ext
+  echo '#line 5184 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5709,7 +5710,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5712: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5713: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7541,7 +7542,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7544 "configure"
+#line 7545 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7639,7 +7640,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7642 "configure"
+#line 7643 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11492,8 +11493,8 @@ fi;
 echo "$as_me:$LINENO: result: ${CONFIG_RTAI_MATH_C99:-no}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_MATH_C99:-no}" >&6
 
-echo "$as_me:$LINENO: checking for vmalloc support in MALLOC" >&5
-echo $ECHO_N "checking for vmalloc support in MALLOC... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for vmalloc use in real-time malloc support" >&5
+echo $ECHO_N "checking for vmalloc use in real-time malloc support... $ECHO_C" >&6
 # Check whether --enable-malloc-vmalloc or --disable-malloc-vmalloc was given.
 if test "${enable_malloc_vmalloc+set}" = set; then
   enableval="$enable_malloc_vmalloc"
@@ -11504,6 +11505,25 @@ if test "${enable_malloc_vmalloc+set}" = set; then
 fi;
 echo "$as_me:$LINENO: result: ${CONFIG_RTAI_MALLOC_VMALLOC:-no}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_MALLOC_VMALLOC:-no}" >&6
+
+echo "$as_me:$LINENO: checking for size of real-time malloc heap" >&5
+echo $ECHO_N "checking for size of real-time malloc heap... $ECHO_C" >&6
+# Check whether --enable-malloc-heap-size or --disable-malloc-heap-size was given.
+if test "${enable_malloc_heap_size+set}" = set; then
+  enableval="$enable_malloc_heap_size"
+  case "$enableval" in
+ 	[0-9]*) CONFIG_RTAI_MALLOC_HEAPSZ=$enableval ;;
+ 	*) { { echo "$as_me:$LINENO: error: Bad argument to option: --enable-malloc-heap-size=<Kbytes>" >&5
+echo "$as_me: error: Bad argument to option: --enable-malloc-heap-size=<Kbytes>" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+fi;
+if test x$CONFIG_RTAI_MALLOC_HEAPSZ = x ; then
+  # Use a reasonable default if unset (in Kbytes)
+  CONFIG_RTAI_MALLOC_HEAPSZ=128
+fi
+echo "$as_me:$LINENO: result: $CONFIG_RTAI_MALLOC_HEAPSZ" >&5
+echo "${ECHO_T}$CONFIG_RTAI_MALLOC_HEAPSZ" >&6
 
 echo "$as_me:$LINENO: checking for number of CPUs (SMP-only)" >&5
 echo $ECHO_N "checking for number of CPUs (SMP-only)... $ECHO_C" >&6
@@ -12454,6 +12474,11 @@ _ACEOF
 
 cat >>confdefs.h <<_ACEOF
 #define CONFIG_RTAI_SCHED_LXRT_NUMSLOTS $CONFIG_RTAI_SCHED_LXRT_NUMSLOTS
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define CONFIG_RTAI_MALLOC_HEAPSZ $CONFIG_RTAI_MALLOC_HEAPSZ
 _ACEOF
 
 if test x$CONFIG_DEVFS_FS = xy; then
