detect whether Linux's COMEDI support is in use

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1005,6 +1005,8 @@ CONFIG_RTAI_LEDS_BUILTIN_TRUE
 CONFIG_RTAI_LEDS_BUILTIN_FALSE
 CONFIG_RTAI_COMEDI_LXRT_TRUE
 CONFIG_RTAI_COMEDI_LXRT_FALSE
+CONFIG_RTAI_USE_LINUX_COMEDI_TRUE
+CONFIG_RTAI_USE_LINUX_COMEDI_FALSE
 CONFIG_RTAI_CPLUSPLUS_TRUE
 CONFIG_RTAI_CPLUSPLUS_FALSE
 CONFIG_RTAI_RTDM_TRUE
@@ -5163,7 +5165,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5166 "configure"' > conftest.$ac_ext
+  echo '#line 5168 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7422,11 +7424,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7425: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7427: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7429: \$? = $ac_status" >&5
+   echo "$as_me:7431: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7690,11 +7692,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7693: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7695: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7697: \$? = $ac_status" >&5
+   echo "$as_me:7699: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7794,11 +7796,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7797: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7799: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7801: \$? = $ac_status" >&5
+   echo "$as_me:7803: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9259,7 +9261,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 9262 "configure"' > conftest.$ac_ext
+    echo '#line 9264 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10123,7 +10125,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10126 "configure"
+#line 10128 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10223,7 +10225,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10226 "configure"
+#line 10228 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12562,11 +12564,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12565: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12567: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12569: \$? = $ac_status" >&5
+   echo "$as_me:12571: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12666,11 +12668,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12669: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12671: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12673: \$? = $ac_status" >&5
+   echo "$as_me:12675: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13202,7 +13204,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 13205 "configure"' > conftest.$ac_ext
+    echo '#line 13207 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -14260,11 +14262,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14263: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14265: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14267: \$? = $ac_status" >&5
+   echo "$as_me:14269: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14364,11 +14366,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14367: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14369: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14371: \$? = $ac_status" >&5
+   echo "$as_me:14373: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15809,7 +15811,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 15812 "configure"' > conftest.$ac_ext
+    echo '#line 15814 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -16586,11 +16588,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16589: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16591: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16593: \$? = $ac_status" >&5
+   echo "$as_me:16595: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16854,11 +16856,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16857: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16859: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16861: \$? = $ac_status" >&5
+   echo "$as_me:16863: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16958,11 +16960,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16961: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16963: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16965: \$? = $ac_status" >&5
+   echo "$as_me:16967: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18423,7 +18425,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 18426 "configure"' > conftest.$ac_ext
+    echo '#line 18428 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -20760,6 +20762,7 @@ fi
 { echo "$as_me:$LINENO: result: ${CONFIG_RTAI_COMEDI_LXRT:-no}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_COMEDI_LXRT:-no}" >&6; }
 
+CONFIG_RTAI_USE_LINUX_COMEDI=n
 if test x$CONFIG_RTAI_COMEDI_LXRT = xy; then
 
 
@@ -20847,6 +20850,9 @@ echo "${ECHO_T}found $COMEDI_DIR" >&6; }
 fi
 
 
+	if test "${RTAI_LINUX_DIR}" = "${CONFIG_RTAI_COMEDI_DIR:0:${#RTAI_LINUX_DIR}}" ; then
+		CONFIG_RTAI_USE_LINUX_COMEDI=y
+	fi
 fi
 
 { echo "$as_me:$LINENO: checking for real-time serial driver" >&5
@@ -24044,6 +24050,11 @@ cat >>confdefs.h <<_ACEOF
 #define CONFIG_RTAI_CAL_FREQS_FACT $CONFIG_RTAI_CAL_FREQS_FACT
 _ACEOF
 
+test x$CONFIG_RTAI_USE_LINUX_COMEDI = xy &&
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTAI_USE_LINUX_COMEDI 1
+_ACEOF
+
 
 case $CONFIG_RTAI_MONITOR_EXECTIME in
 	y) CONFIG_RTAI_MONITOR_EXECTIME=1 ;;
@@ -24602,6 +24613,14 @@ fi
 else
   CONFIG_RTAI_COMEDI_LXRT_TRUE='#'
   CONFIG_RTAI_COMEDI_LXRT_FALSE=
+fi
+
+ if test x$CONFIG_RTAI_USE_LINUX_COMEDI = xy; then
+  CONFIG_RTAI_USE_LINUX_COMEDI_TRUE=
+  CONFIG_RTAI_USE_LINUX_COMEDI_FALSE='#'
+else
+  CONFIG_RTAI_USE_LINUX_COMEDI_TRUE='#'
+  CONFIG_RTAI_USE_LINUX_COMEDI_FALSE=
 fi
 
  if test x$CONFIG_RTAI_CPLUSPLUS = xy; then
@@ -25643,6 +25662,13 @@ if test -z "${CONFIG_RTAI_COMEDI_LXRT_TRUE}" && test -z "${CONFIG_RTAI_COMEDI_LX
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_COMEDI_LXRT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTAI_COMEDI_LXRT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTAI_USE_LINUX_COMEDI_TRUE}" && test -z "${CONFIG_RTAI_USE_LINUX_COMEDI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_USE_LINUX_COMEDI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTAI_USE_LINUX_COMEDI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26713,6 +26739,8 @@ CONFIG_RTAI_LEDS_BUILTIN_TRUE!$CONFIG_RTAI_LEDS_BUILTIN_TRUE$ac_delim
 CONFIG_RTAI_LEDS_BUILTIN_FALSE!$CONFIG_RTAI_LEDS_BUILTIN_FALSE$ac_delim
 CONFIG_RTAI_COMEDI_LXRT_TRUE!$CONFIG_RTAI_COMEDI_LXRT_TRUE$ac_delim
 CONFIG_RTAI_COMEDI_LXRT_FALSE!$CONFIG_RTAI_COMEDI_LXRT_FALSE$ac_delim
+CONFIG_RTAI_USE_LINUX_COMEDI_TRUE!$CONFIG_RTAI_USE_LINUX_COMEDI_TRUE$ac_delim
+CONFIG_RTAI_USE_LINUX_COMEDI_FALSE!$CONFIG_RTAI_USE_LINUX_COMEDI_FALSE$ac_delim
 CONFIG_RTAI_CPLUSPLUS_TRUE!$CONFIG_RTAI_CPLUSPLUS_TRUE$ac_delim
 CONFIG_RTAI_CPLUSPLUS_FALSE!$CONFIG_RTAI_CPLUSPLUS_FALSE$ac_delim
 CONFIG_RTAI_RTDM_TRUE!$CONFIG_RTAI_RTDM_TRUE$ac_delim
@@ -26767,8 +26795,6 @@ RTAI_LINUX_VERSION!$RTAI_LINUX_VERSION$ac_delim
 RTAI_MODULE_DIR!$RTAI_MODULE_DIR$ac_delim
 RTAI_MODULE_EXT!$RTAI_MODULE_EXT$ac_delim
 RTAI_KBUILD_ENV!$RTAI_KBUILD_ENV$ac_delim
-RTAI_KBUILD_TOP!$RTAI_KBUILD_TOP$ac_delim
-RTAI_KBUILD_BOTTOM!$RTAI_KBUILD_BOTTOM$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -26810,6 +26836,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+RTAI_KBUILD_TOP!$RTAI_KBUILD_TOP$ac_delim
+RTAI_KBUILD_BOTTOM!$RTAI_KBUILD_BOTTOM$ac_delim
 RTAI_KBUILD_CMD!$RTAI_KBUILD_CMD$ac_delim
 RTAI_KBUILD_CLEAN!$RTAI_KBUILD_CLEAN$ac_delim
 RTAI_KBUILD_DISTCLEAN!$RTAI_KBUILD_DISTCLEAN$ac_delim
@@ -26823,7 +26851,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 13; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
