check for MMU only meaningful in >2.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20001,28 +20001,34 @@ fi
 { echo "$as_me:$LINENO: result: $wanted_kernel_arch" >&5
 echo "${ECHO_T}$wanted_kernel_arch" >&6; }
 
-{ echo "$as_me:$LINENO: checking for MMU support" >&5
+case "${RTAI_LINUX_VERSION}" in
+2.4.*)
+		;;
+*)
+	{ echo "$as_me:$LINENO: checking for MMU support" >&5
 echo $ECHO_N "checking for MMU support... $ECHO_C" >&6; }
-mmu_select=`eval echo \\$CONFIG_MMU`
-if test x$mmu_select != x$arch_has_mmu; then
-   echo
-   echo "************************************************************"
-   echo " The target RTAI architecture MMU check failed:"
-if test x$mmu_select = x; then
-   echo " MMU is unsupported by Linux architecure."
-else
-   echo " MMU is supported by Linux architecure, but it shouldn\'t."
-fi
-   echo "************************************************************"
-   exit 1
-fi
-if test x$mmu_select != x; then
-{ echo "$as_me:$LINENO: result: yes" >&5
+	mmu_select=`eval echo \\$CONFIG_MMU`
+	if test x$mmu_select != x$arch_has_mmu; then
+		echo
+		echo "************************************************************"
+		echo " The target RTAI architecture MMU check failed:"
+		if test x$mmu_select = x; then
+			echo " MMU is unsupported by Linux architecure."
+		else
+			echo " MMU is supported by Linux architecure, but it shouldn\'t."
+		fi
+		echo "************************************************************"
+		exit 1
+	fi
+	if test x$mmu_select != x; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-else
-{ echo "$as_me:$LINENO: result: no" >&5
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-fi
+	fi
+	;;
+esac
 
 if test x${CONFIG_MODULES} = x ; then
   { { echo "$as_me:$LINENO: error: Please set CONFIG_MODULES for $RTAI_LINUX_DIR and rebuild your kernel" >&5
