RTAI 3.7 development cycle starts

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,11 +1,11 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_PREREQ(2.59)
 
-AC_INIT(rtai,3.6-cv,rtai@rtai.org)
+AC_INIT(rtai,3.7-test1,rtai@rtai.org)
 
 CONFIG_RTAI_VERSION_MAJOR=3
-CONFIG_RTAI_VERSION_MINOR=6-cv
-#CONFIG_RTAI_REVISION_LEVEL=2
+CONFIG_RTAI_VERSION_MINOR=7-test1
+#CONFIG_RTAI_REVISION_LEVEL=0
 
 AC_CONFIG_HEADERS(rtai_config.h)
 AC_CONFIG_AUX_DIR(base/config/autoconf)
@@ -25,6 +25,18 @@ AC_ARG_WITH(CC,
 	esac
 	CC="$withval"
     ])
+
+CROSS_COMPILE=
+case "$host" in
+ m68knommu-*)
+	LDFLAGS="-Wl,-elf2flt"
+	enable_shared=no
+	CROSSCOMPILE_TEST="tools/ucfront-gcc "$CROSS_COMPILE"gcc"
+	;;
+esac
+AC_MSG_CHECKING([for CROSS_COMPILE])
+AC_MSG_RESULT([$CROSS_COMPILE])
+
 AC_PROG_CC
 CFLAGS=""
 
@@ -57,6 +69,7 @@ arch_supports_lxrt=
 arch_supports_leds=
 arch_supports_sim=
 arch_supports_rtailab=
+arch_has_mmu=y
 
 case "$host" in
  i*86*-*)
@@ -81,6 +94,11 @@ case "$host" in
 	RTAI_TARGET_ARCH=ppc
 	wanted_kernel_arch=CONFIG_PPC
         ;;
+ m68knommu-*)
+ 	RTAI_TARGET_ARCH=m68knommu
+	wanted_kernel_arch=CONFIG_M68K
+	arch_has_mmu=
+	;;
  *) echo ""
    echo "*******************************************"
    echo "Still unsupported host: $host -- Sorry."
@@ -263,8 +281,10 @@ dnl
 dnl Perform a few sanity checks.
 dnl
 
+AC_MSG_CHECKING([for kernel architecture])
 arch_select=`eval echo \\$$wanted_kernel_arch`
 if test x$arch_select = x; then
+   AC_MSG_RESULT([FAIL])
    echo
    echo "************************************************************"
    echo " The target RTAI architecture ($RTAI_TARGET_ARCH) does not match"
@@ -272,6 +292,27 @@ if test x$arch_select = x; then
    echo " (i.e. $wanted_kernel_arch is undefined)"
    echo "************************************************************"
    exit 1
+fi
+AC_MSG_RESULT([$wanted_kernel_arch])
+
+AC_MSG_CHECKING([for MMU support])
+mmu_select=`eval echo \\$CONFIG_MMU`
+if test x$mmu_select != x$arch_has_mmu; then
+   echo
+   echo "************************************************************"
+   echo " The target RTAI architecture MMU check failed:"
+if test x$mmu_select = x; then
+   echo " MMU is unsupported by Linux architecure."
+else
+   echo " MMU is supported by Linux architecure, but it shouldn\'t."
+fi
+   echo "************************************************************"
+   exit 1
+fi
+if test x$mmu_select != x; then
+AC_MSG_RESULT([yes])
+else
+AC_MSG_RESULT([no])
 fi
 
 if test x${CONFIG_MODULES} = x ; then
@@ -399,6 +440,24 @@ if test x$CONFIG_RTAI_SEM = xy ; then
   RTAI_BUILTIN_MODLIST="$RTAI_BUILTIN_MODLIST ipc/sem"
 fi
 
+AC_MSG_CHECKING(for RT POLL support)
+AC_ARG_ENABLE(rt-poll,
+	[ --enable-rt-poll		enable polling support of RTAI IPCs],
+	[case "$enableval" in
+	y | yes) CONFIG_RTAI_RT_POLL=y ;;
+	*) unset CONFIG_RTAI_RT_POLL ;;
+	esac])
+AC_MSG_RESULT(${CONFIG_RTAI_RT_POLL:-no})
+
+AC_MSG_CHECKING(for RT POLL on stack)
+AC_ARG_ENABLE(rt-poll-on-stack,
+	[ --enable-rt-poll-on-stack	Use the stack for rt_poll dynamic arrays],
+	[case "$enableval" in
+	y | yes) CONFIG_RTAI_RT_POLL_ON_STACK=y ;;
+	*) unset CONFIG_RTAI_RT_POLL_ON_STACK ;;
+	esac])
+AC_MSG_RESULT(${CONFIG_RTAI_RT_POLL_ON_STACK:-no})
+
 AC_MSG_CHECKING(for messaging support)
 AC_ARG_ENABLE(mbx,
 	[ --enable-msg		Enable messaging support],
@@ -502,14 +561,9 @@ AC_ARG_ENABLE(usi,
 	[ --enable-usi		Enable user-space interrupt support],
 	[case "$enableval" in
 	y | yes | b | builtin | built-in) CONFIG_RTAI_USI=y ;;
-	m | mod | module) CONFIG_RTAI_USI=m ;;
 	*) unset CONFIG_RTAI_USI ;;
 	esac])
 AC_MSG_RESULT(${CONFIG_RTAI_USI:-no})
-
-if test x$CONFIG_RTAI_USI = xy ; then
-  RTAI_BUILTIN_MODLIST="$RTAI_BUILTIN_MODLIST usi"
-fi
 
 AC_MSG_CHECKING(for watchdog support)
 AC_ARG_ENABLE(watchdog,
@@ -629,6 +683,16 @@ if test x$CONFIG_RTAI_SCHED_LXRT_NUMSLOTS = x ; then
 fi
 AC_MSG_RESULT($CONFIG_RTAI_SCHED_LXRT_NUMSLOTS)
 
+AC_MSG_CHECKING(for RTDM support)
+AC_ARG_ENABLE(rtdm,
+	[ --enable-rtdm		Enable RTDM support],
+	[case "$enableval" in
+	y | yes | b | builtin | built-in) CONFIG_RTAI_RTDM=y ;;
+	m | mod | module) CONFIG_RTAI_RTDM=m ;;
+	*) unset CONFIG_RTAI_RTDM ;;
+	esac])
+AC_MSG_RESULT(${CONFIG_RTAI_RTDM:-no})
+
 AC_MSG_CHECKING(for maximum file descriptors in RTDM)
 AC_ARG_ENABLE(rtdm-fd-max,
 	      [ --enable-rtdm-fd-max        	Set maximum number of RTDM file descriptor slots],
@@ -659,6 +723,15 @@ AC_ARG_ENABLE(rtdm-shirq,
 	*) unset CONFIG_RTAI_RTDM_SHIRQ ;;
 	esac])
 AC_MSG_RESULT(${CONFIG_RTAI_RTDM_SHIRQ:-no})
+
+AC_MSG_CHECKING(for select(2) support in RTDM)
+AC_ARG_ENABLE(rtdm-select,
+	      [ --enable-rtdm-select	Enable select support in RTDM],
+	[case "$enableval" in
+	y | yes) CONFIG_RTAI_RTDM_SELECT=y ;;
+	*) unset CONFIG_RTAI_RTDM_SELECT ;;
+	esac])
+AC_MSG_RESULT(${CONFIG_RTAI_RTDM_SELECT:-no})
 
 AC_MSG_CHECKING(for RTDM debug)
 AC_ARG_ENABLE(debug-rtdm,
@@ -1133,6 +1206,18 @@ if test x$CONFIG_RTAI_NETRPC = xy ; then
    fi
 fi
 
+if test x$CONFIG_RTAI_RT_POLL = xy ; then
+   if test x$CONFIG_RTAI_SEM = x ; then
+      AC_MSG_ERROR([--enable-rt-poll requires --enable-sem])
+   fi
+fi
+
+if test x$CONFIG_RTAI_RT_POLL_ON_STACK = xy ; then
+   if test x$CONFIG_RTAI_RT_POLL = x ; then
+      AC_MSG_ERROR([--enable-rt-poll-on-stack requires --enable-rt-poll])
+   fi
+fi
+
 if test x$CONFIG_RTAI_MBX = xy -o x$CONFIG_RTAI_MBX = xm ; then
    if test x$CONFIG_RTAI_SEM = x ; then
       AC_MSG_ERROR([--enable-mbx requires --enable-sem])
@@ -1169,15 +1254,15 @@ if test x$CONFIG_RTAI_MQ = xy ; then
    fi
 fi
 
-if test x$CONFIG_RTAI_USI = xy -o x$CONFIG_RTAI_USI = xm ; then
-   if test x$CONFIG_RTAI_SEM = x -o x$CONFIG_RTAI_TASKLETS = x; then
-      AC_MSG_ERROR([--enable-usi requires --enable-sem and --enable-tasklets])
+if test x$CONFIG_RTAI_RTDM_SELECT = xy ; then
+   if test x$CONFIG_RTAI_RTDM = x ; then
+      AC_MSG_ERROR([--enable-rtdm-select=y requires --enable-rtdm=y])
    fi
 fi
 
-if test x$CONFIG_RTAI_USI = xy ; then
-   if test x$CONFIG_RTAI_SEM = xm -o x$CONFIG_RTAI_TASKLETS = xm; then
-      AC_MSG_ERROR([--enable-usi=y requires --enable-sem=y and --enable-tasklets=y])
+if test x$CONFIG_RTAI_RTDM_SHIRQ = xy ; then
+   if test x$CONFIG_RTAI_RTDM = x ; then
+      AC_MSG_ERROR([--enable-rtdm-shirq=y requires --enable-rtdm=y])
    fi
 fi
 
@@ -1231,6 +1316,8 @@ test \! x$CONFIG_RTAI_FIFOS = x && AC_DEFINE(CONFIG_RTAI_FIFOS,1,[Kconfig])
 test \! x$CONFIG_RTAI_NETRPC = x && AC_DEFINE(CONFIG_RTAI_NETRPC,1,[Kconfig])
 test x$CONFIG_RTAI_NETRPC_RTNET = xy && AC_DEFINE(CONFIG_RTAI_NETRPC_RTNET,1,[Kconfig])
 test \! x$CONFIG_RTAI_SEM = x && AC_DEFINE(CONFIG_RTAI_SEM,1,[Kconfig])
+test \! x$CONFIG_RTAI_RT_POLL = x && AC_DEFINE(CONFIG_RTAI_RT_POLL,1,[Kconfig])
+test \! x$CONFIG_RTAI_RT_POLL_ON_STACK = x && AC_DEFINE(CONFIG_RTAI_RT_POLL_ON_STACK,1,[Kconfig])
 test \! x$CONFIG_RTAI_MSG = x && AC_DEFINE(CONFIG_RTAI_MSG,1,[Kconfig])
 test \! x$CONFIG_RTAI_MBX = x && AC_DEFINE(CONFIG_RTAI_MBX,1,[Kconfig])
 test \! x$CONFIG_RTAI_TBX = x && AC_DEFINE(CONFIG_RTAI_TBX,1,[Kconfig])
@@ -1281,6 +1368,7 @@ AC_DEFINE_UNQUOTED(CONFIG_RTAI_SCHED_APIC_LATENCY,$CONFIG_RTAI_SCHED_APIC_LATENC
 AC_DEFINE_UNQUOTED(CONFIG_RTAI_SCHED_LXRT_NUMSLOTS,$CONFIG_RTAI_SCHED_LXRT_NUMSLOTS,[Kconfig])
 AC_DEFINE_UNQUOTED(CONFIG_RTAI_RTDM_FD_MAX,$CONFIG_RTAI_RTDM_FD_MAX,[Kconfig])
 test x$CONFIG_RTAI_RTDM_SHIRQ = xy && AC_DEFINE(CONFIG_RTAI_RTDM_SHIRQ,1,[Kconfig])
+test x$CONFIG_RTAI_RTDM_SELECT = xy && AC_DEFINE(CONFIG_RTAI_RTDM_SELECT,1,[Kconfig])
 test x$CONFIG_RTAI_DEBUG_RTDM = xy && AC_DEFINE(CONFIG_RTAI_DEBUG_RTDM,1,[Kconfig])
 AC_DEFINE_UNQUOTED(CONFIG_RTAI_CAL_FREQS_FACT,$CONFIG_RTAI_CAL_FREQS_FACT,[Kconfig])
 
@@ -1342,7 +1430,12 @@ test x$CONFIG_RTAI_MAINTAINER = xy && AC_DEFINE(CONFIG_RTAI_MAINTAINER,1,[Kconfi
 test x$CONFIG_RTAI_MAINTAINER_PMA = xy && AC_DEFINE(CONFIG_RTAI_MAINTAINER_PMA,1,[Kconfig])
 test x$CONFIG_RTAI_MAINTAINER_PGM = xy && AC_DEFINE(CONFIG_RTAI_MAINTAINER_PGM,1,[Kconfig])
 
-test x$arch_supports_lxrt = xy && AC_DEFINE(CONFIG_RTAI_INTERNAL_LXRT_SUPPORT,1,[Kconfig])
+if test x$arch_supports_lxrt = xy;  then
+    AC_DEFINE(CONFIG_RTAI_INTERNAL_LXRT_SUPPORT,1,[Kconfig])
+else
+    AC_DEFINE(CONFIG_RTAI_INTERNAL_LXRT_SUPPORT,0,[Kconfig])
+fi
+
 test x$arch_supports_leds = xy && AC_DEFINE(CONFIG_RTAI_INTERNAL_LEDS_SUPPORT,1,[Kconfig])
 AC_DEFINE_UNQUOTED(CONFIG_RTAI_INTERNAL_LXRT_INLINE,$CONFIG_RTAI_LXRT_INLINE,[Kconfig])
 
@@ -1407,6 +1500,9 @@ AM_CONDITIONAL(CONFIG_ARCH_EP9301,[test "$CONFIG_ARCH_EP9301" = y])
 AM_CONDITIONAL(CONFIG_ARCH_PXA,[test "$CONFIG_ARCH_PXA" = y])
 AM_CONDITIONAL(CONFIG_UCLINUX,[test "$CONFIG_UCLINUX" = y])
 AM_CONDITIONAL(CONFIG_SMP,[test "$CONFIG_SMP" = y])
+AM_CONDITIONAL(CONFIG_M68KNOMMU,[test "$CONFIG_M68K" = y -a "x$CONFIG_MMU" != xy])
+AM_CONDITIONAL(CONFIG_M5407,[test "$CONFIG_M5407" = y])
+AM_CONDITIONAL(CONFIG_M5329,[test "$CONFIG_M5329" = y])
 
 AM_CONDITIONAL(CONFIG_RTAI_TRACE,[test -n "$CONFIG_RTAI_TRACE"])
 AM_CONDITIONAL(CONFIG_RTAI_MATH,[test -n "$CONFIG_RTAI_MATH"])
@@ -1414,6 +1510,8 @@ AM_CONDITIONAL(CONFIG_RTAI_BITS,[test -n "$CONFIG_RTAI_BITS"])
 AM_CONDITIONAL(CONFIG_RTAI_FIFOS,[test -n "$CONFIG_RTAI_FIFOS"])
 AM_CONDITIONAL(CONFIG_RTAI_NETRPC,[test -n "$CONFIG_RTAI_NETRPC"])
 AM_CONDITIONAL(CONFIG_RTAI_SEM,[test -n "$CONFIG_RTAI_SEM"])
+AM_CONDITIONAL(CONFIG_RTAI_RT_POLL,[test -n "$CONFIG_RTAI_RT_POLL"])
+AM_CONDITIONAL(CONFIG_RTAI_RT_POLL_ON_STACK,[test -n "$CONFIG_RTAI_RT_POLL_ON_STACK"])
 AM_CONDITIONAL(CONFIG_RTAI_MSG,[test -n "$CONFIG_RTAI_MSG"])
 AM_CONDITIONAL(CONFIG_RTAI_MBX,[test -n "$CONFIG_RTAI_MBX"])
 AM_CONDITIONAL(CONFIG_RTAI_TBX,[test -n "$CONFIG_RTAI_TBX"])
@@ -1600,6 +1698,32 @@ case $RTAI_TARGET_ARCH in
 	   RTAI_FP_CFLAGS="$RTAI_FP_CFLAGS -msoft-float"
 	fi
 	;;
+ m68knommu)
+	if test "$CONFIG_M5407" = y; then
+               RTAI_TARGET_SUBARCH=MCF5407
+               CFLAGS="-m5407 -Wa,-m5407"
+	elif test "$CONFIG_M532x" = y; then
+               RTAI_TARGET_SUBARCH=MCF5329
+               CFLAGS="-m5307 -Wa,-m5307"
+	else
+	   echo
+	   echo "************************************************"
+	   echo "Unsupported M68KNOMMU sub-architecture -- Sorry."
+	   echo "************************************************"
+	   exit 1
+	fi
+	RTAI_KMOD_CFLAGS="$RTAI_KMOD_CFLAGS -I${RTAI_LINUX_DIR}/arch/m68knommu -DCONFIG_UCLINUX"
+	RTAI_KMOD_CXXFLAGS="$RTAI_KMOD_CFLAGS -fno-rtti -fno-exceptions -fno-strength-reduce -pipe"
+	RTAI_USER_CFLAGS="$RTAI_USER_CFLAGS -Wall -Wstrict-prototypes -pipe -DCONFIG_UCLINUX"
+	RTAI_FP_CFLAGS="$RTAI_FP_CFLAGS -DCONFIG_UCLINUX"
+	if test x$CONFIG_RTAI_FPU_SUPPORT = xy; then
+	   RTAI_FP_CFLAGS="$RTAI_FP_CFLAGS -mhard-float"
+	else
+	   RTAI_FP_CFLAGS="$RTAI_FP_CFLAGS -msoft-float"
+	fi
+	;;
+
+
 esac
 
 if test x$CONFIG_RTAI_KMOD_DEBUG = xy; then
@@ -1730,6 +1854,7 @@ AC_SUBST(RTAI_KBUILD_DISTCLEAN)
 AC_SUBST(RTAI_POSIX_WRAP)
 
 AC_SUBST(CONFIG_RTAI_LINUXDIR)
+AC_SUBST(CROSSCOMPILE_TEST)
 
 
 AC_CONFIG_FILES([ \
@@ -1758,6 +1883,9 @@ AC_CONFIG_FILES([ \
         base/arch/ppc/GNUmakefile \
 	base/arch/ppc/hal/GNUmakefile \
 	base/include/asm-ppc/GNUmakefile \
+	base/arch/m68knommu/GNUmakefile \
+	base/arch/m68knommu/hal/GNUmakefile \
+	base/include/asm-m68knommu/GNUmakefile \
    	base/ipc/bits/GNUmakefile \
 	base/ipc/fifos/GNUmakefile \
 	base/ipc/netrpc/GNUmakefile \
