see changelog

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1069,22 +1069,22 @@ Optional Features:
  --enable-usi		Enable user-space interrupt support
  --enable-watchdog	Enable watchdog support
  --enable-leds		Enable leds-based debugging support
- --enable-lxrt-use-linux-syscall		Wrap LXRT service calls throug Linux syscall mechanism
+ --enable-lxrt-use-linux-syscall	Wrap LXRT service calls throug Linux syscall mechanism
  --enable-sched-up	Enable UP scheduler support
  --enable-sched-smp	Enable SMP scheduler support
  --enable-sched-mup	Enable MUP scheduler support
  --enable-sched-lxrt	Enable LXRT scheduler support
  --enable-ktasks-sched-lxrt	Enable LXRT scheduler with kernel tasks support
  --enable-sched-lock-isr	Enable scheduler lock in ISRs
- --enable-rtc-freq Enable RTC freq
+ --enable-rtc-freq	Enable RTC freq
  --enable-long-timed-lists	Enable long timed lists
  --enable-sched-8254-latency	Set 8254 tuning latency
  --enable-sched-apic-latency	Set APIC tuning latency
  --enable-sched-lxrt-numslots	Set maximum number of LXRT slots
  --enable-rtdm-fd-max        	Set maximum number of RTDM file descriptor slots
- --enable-rtdm-edge-shirq        	Enable shared edge triggered interrupts in RTDM
- --enable-rtdm-level-shirq        	Enable shared level triggered interrupts in RTDM
- --enable-debug-rtdm			Enable RTDM debug
+ --enable-rtdm-edge-shirq	Enable shared edge triggered interrupts in RTDM
+ --enable-rtdm-level-shirq	Enable shared level triggered interrupts in RTDM
+ --enable-debug-rtdm		Enable RTDM debug
  --enable-cplusplus	Build in-kernel C++ support
  --enable-cal-freq-fact      	Set calibration frequency factor
  --enable-comedi-lxrt	Enable comedi/LXRT support
@@ -1098,6 +1098,9 @@ Optional Features:
  --enable-malloc-vmalloc	Enable vmalloc support in malloc
  --enable-malloc-heap-size	Set size of real-time malloc heap
  --enable-cpus		Enable CPUs
+ --enable-diag-tsc-sync		Enable diagnose out of sync MP-TSCs
+ --enable-master-tsc-cpu	Enable master TSC CPU
+ --enable-tune-tsc-sync		Enable tune out of sync MP-TSCs
  --enable-dox-doc	Build Doxygen documentation
 --enable-dbx	Build Docbook XML documentation.
 --enable-dbx-network	Try to access Docbook DTD and
@@ -4292,7 +4295,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4295 "configure"' > conftest.$ac_ext
+  echo '#line 4298 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5407,7 +5410,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5410:" \
+echo "$as_me:5413:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6505,11 +6508,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6508: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6511: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6512: \$? = $ac_status" >&5
+   echo "$as_me:6515: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6767,11 +6770,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6770: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6773: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6774: \$? = $ac_status" >&5
+   echo "$as_me:6777: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6829,11 +6832,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6832: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6835: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6836: \$? = $ac_status" >&5
+   echo "$as_me:6839: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9069,7 +9072,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9072 "configure"
+#line 9075 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9167,7 +9170,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9170 "configure"
+#line 9173 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11415,11 +11418,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11418: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11421: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11422: \$? = $ac_status" >&5
+   echo "$as_me:11425: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11477,11 +11480,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11480: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11483: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11484: \$? = $ac_status" >&5
+   echo "$as_me:11487: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12846,7 +12849,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12849 "configure"
+#line 12852 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12944,7 +12947,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12947 "configure"
+#line 12950 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13829,11 +13832,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13832: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13835: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13836: \$? = $ac_status" >&5
+   echo "$as_me:13839: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13891,11 +13894,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13894: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13897: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13898: \$? = $ac_status" >&5
+   echo "$as_me:13901: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16013,11 +16016,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16016: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16020: \$? = $ac_status" >&5
+   echo "$as_me:16023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16275,11 +16278,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16278: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16281: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16282: \$? = $ac_status" >&5
+   echo "$as_me:16285: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16337,11 +16340,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16340: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16343: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16344: \$? = $ac_status" >&5
+   echo "$as_me:16347: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18577,7 +18580,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18580 "configure"
+#line 18583 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18675,7 +18678,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18678 "configure"
+#line 18681 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23098,6 +23101,59 @@ echo "$as_me:$LINENO: result: ${CONFIG_RTAI_CPUS:-1}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_CPUS:-1}" >&6
 
 
+echo "$as_me:$LINENO: checking for diagnose out of sync MP-TSCs" >&5
+echo $ECHO_N "checking for diagnose out of sync MP-TSCs... $ECHO_C" >&6
+# Check whether --enable-diag-tsc-sync or --disable-diag-tsc-sync was given.
+if test "${enable_diag_tsc_sync+set}" = set; then
+  enableval="$enable_diag_tsc_sync"
+  case "$enableval" in
+	y | yes) CONFIG_RTAI_DIAG_TSC_SYNC=y ;;
+	*) unset CONFIG_RTAI_DIAG_TSC_SYNC ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTAI_DIAG_TSC_SYNC:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTAI_DIAG_TSC_SYNC:-no}" >&6
+
+echo "$as_me:$LINENO: checking for master CPU for aligning MP-TSCs" >&5
+echo $ECHO_N "checking for master CPU for aligning MP-TSCs... $ECHO_C" >&6
+# Check whether --enable-master-tsc-cpu or --disable-master-tsc-cpu was given.
+if test "${enable_master_tsc_cpu+set}" = set; then
+  enableval="$enable_master_tsc_cpu"
+  case "$enableval" in
+         [0-7])
+ 		if test x$CONFIG_RTAI_CPUS = x ; then
+			{ { echo "$as_me:$LINENO: error: Option --enable-cpus must be defined before --enable-master-tsc-cpu" >&5
+echo "$as_me: error: Option --enable-cpus must be defined before --enable-master-tsc-cpu" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+		if test $enableval -lt 0 -o $enableval -ge $CONFIG_RTAI_CPUS ; then
+			{ { echo "$as_me:$LINENO: error: Invalid value to option: --enable-master-tsc-cpu=<master-CPU-number> (must be between 0 and CONFIG_RTAI_CPUS)" >&5
+echo "$as_me: error: Invalid value to option: --enable-master-tsc-cpu=<master-CPU-number> (must be between 0 and CONFIG_RTAI_CPUS)" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+		CONFIG_RTAI_MASTER_TSC_CPU=$enableval ;;
+	*) { { echo "$as_me:$LINENO: error: Bad argument to option: --enable-master-tsc-cpu=<master-CPU-number>" >&5
+echo "$as_me: error: Bad argument to option: --enable-master-tsc-cpu=<master-CPU-number>" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTAI_MASTER_TSC_CPU:0}" >&5
+echo "${ECHO_T}${CONFIG_RTAI_MASTER_TSC_CPU:0}" >&6
+
+echo "$as_me:$LINENO: checking for tune out of sync MP-TSCs" >&5
+echo $ECHO_N "checking for tune out of sync MP-TSCs... $ECHO_C" >&6
+# Check whether --enable-tune-tsc-sync or --disable-tune-tsc-sync was given.
+if test "${enable_tune_tsc_sync+set}" = set; then
+  enableval="$enable_tune_tsc_sync"
+  case "$enableval" in
+	y | yes) CONFIG_RTAI_TUNE_TSC_SYNC=y ;;
+	*) unset CONFIG_RTAI_TUNE_TSC_SYNC ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTAI_TUNE_TSC_SYNC:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTAI_TUNE_TSC_SYNC:-no}" >&6
+
+
 if test \! -d $srcdir/doc; then
     unset RTAI_MAYBE_DOCDIR
 else
@@ -23826,6 +23882,21 @@ _ACEOF
 test \! x$CONFIG_RTAI_CPUS = x &&
 cat >>confdefs.h <<_ACEOF
 #define CONFIG_RTAI_CPUS $CONFIG_RTAI_CPUS
+_ACEOF
+
+test x$CONFIG_RTAI_DIAG_TSC_SYNC = xy &&
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTAI_DIAG_TSC_SYNC 1
+_ACEOF
+
+test \! x$CONFIG_RTAI_MASTER_TSC_CPU = x &&
+cat >>confdefs.h <<_ACEOF
+#define CONFIG_RTAI_MASTER_TSC_CPU $CONFIG_RTAI_MASTER_TSC_CPU
+_ACEOF
+
+test x$CONFIG_RTAI_TUNE_TSC_SYNC = xy &&
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTAI_TUNE_TSC_SYNC 1
 _ACEOF
 
 test \! x$CONFIG_RTAI_FPU_SUPPORT = x &&
