Correctly handle the --with-linux-dir configure option.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all rtai-sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GL_CFLAGS GL_LIBS RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE RTAI_MAYBE_SIMDIR CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_ARM_TRUE CONFIG_ARM_FALSE CONFIG_ARCH_SA1100_TRUE CONFIG_ARCH_SA1100_FALSE CONFIG_ARCH_CLPS711X_TRUE CONFIG_ARCH_CLPS711X_FALSE CONFIG_ARCH_PXA_TRUE CONFIG_ARCH_PXA_FALSE CONFIG_MIPS_TRUE CONFIG_MIPS_FALSE CONFIG_CRIS_TRUE CONFIG_CRIS_FALSE CONFIG_UCLINUX_TRUE CONFIG_UCLINUX_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_SCHED_UP_TRUE CONFIG_RTAI_SCHED_UP_FALSE CONFIG_RTAI_SCHED_MUP_TRUE CONFIG_RTAI_SCHED_MUP_FALSE CONFIG_RTAI_SCHED_SMP_TRUE CONFIG_RTAI_SCHED_SMP_FALSE CONFIG_RTAI_SCHED_LXRT_TRUE CONFIG_RTAI_SCHED_LXRT_FALSE CONFIG_RTAI_XENOMAI_TRUE CONFIG_RTAI_XENOMAI_FALSE CONFIG_RTAI_TRACE_TRUE CONFIG_RTAI_TRACE_FALSE CONFIG_RTAI_MATH_TRUE CONFIG_RTAI_MATH_FALSE CONFIG_RTAI_BITS_TRUE CONFIG_RTAI_BITS_FALSE CONFIG_RTAI_FIFOS_TRUE CONFIG_RTAI_FIFOS_FALSE CONFIG_RTAI_NETRPC_TRUE CONFIG_RTAI_NETRPC_FALSE CONFIG_RTAI_SEM_TRUE CONFIG_RTAI_SEM_FALSE CONFIG_RTAI_MSG_TRUE CONFIG_RTAI_MSG_FALSE CONFIG_RTAI_MBX_TRUE CONFIG_RTAI_MBX_FALSE CONFIG_RTAI_TBX_TRUE CONFIG_RTAI_TBX_FALSE CONFIG_RTAI_MQ_TRUE CONFIG_RTAI_MQ_FALSE CONFIG_RTAI_SHM_TRUE CONFIG_RTAI_SHM_FALSE CONFIG_RTAI_MALLOC_TRUE CONFIG_RTAI_MALLOC_FALSE CONFIG_RTAI_TASKLETS_TRUE CONFIG_RTAI_TASKLETS_FALSE CONFIG_RTAI_USI_TRUE CONFIG_RTAI_USI_FALSE CONFIG_RTAI_WD_TRUE CONFIG_RTAI_WD_FALSE CONFIG_RTAI_LEDS_TRUE CONFIG_RTAI_LEDS_FALSE CONFIG_RTAI_MATH_BUILTIN_TRUE CONFIG_RTAI_MATH_BUILTIN_FALSE CONFIG_RTAI_BITS_BUILTIN_TRUE CONFIG_RTAI_BITS_BUILTIN_FALSE CONFIG_RTAI_FIFOS_BUILTIN_TRUE CONFIG_RTAI_FIFOS_BUILTIN_FALSE CONFIG_RTAI_NETRPC_BUILTIN_TRUE CONFIG_RTAI_NETRPC_BUILTIN_FALSE CONFIG_RTAI_SEM_BUILTIN_TRUE CONFIG_RTAI_SEM_BUILTIN_FALSE CONFIG_RTAI_MSG_BUILTIN_TRUE CONFIG_RTAI_MSG_BUILTIN_FALSE CONFIG_RTAI_MBX_BUILTIN_TRUE CONFIG_RTAI_MBX_BUILTIN_FALSE CONFIG_RTAI_TBX_BUILTIN_TRUE CONFIG_RTAI_TBX_BUILTIN_FALSE CONFIG_RTAI_MQ_BUILTIN_TRUE CONFIG_RTAI_MQ_BUILTIN_FALSE CONFIG_RTAI_SHM_BUILTIN_TRUE CONFIG_RTAI_SHM_BUILTIN_FALSE CONFIG_RTAI_MALLOC_BUILTIN_TRUE CONFIG_RTAI_MALLOC_BUILTIN_FALSE CONFIG_RTAI_TASKLETS_BUILTIN_TRUE CONFIG_RTAI_TASKLETS_BUILTIN_FALSE CONFIG_RTAI_USI_BUILTIN_TRUE CONFIG_RTAI_USI_BUILTIN_FALSE CONFIG_RTAI_LEDS_BUILTIN_TRUE CONFIG_RTAI_LEDS_BUILTIN_FALSE CONFIG_RTAI_COMEDI_LXRT_TRUE CONFIG_RTAI_COMEDI_LXRT_FALSE CONFIG_RTAI_CPLUSPLUS_TRUE CONFIG_RTAI_CPLUSPLUS_FALSE CONFIG_RTAI_SERIAL_TRUE CONFIG_RTAI_SERIAL_FALSE CONFIG_RTAI_XENOMAI_SKIN_PSOS_TRUE CONFIG_RTAI_XENOMAI_SKIN_PSOS_FALSE CONFIG_RTAI_XENOMAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_XENOMAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_XENOMAI_SKIN_VRTX_TRUE CONFIG_RTAI_XENOMAI_SKIN_VRTX_FALSE CONFIG_RTAI_XENOMAI_SKIN_UITRON_TRUE CONFIG_RTAI_XENOMAI_SKIN_UITRON_FALSE CONFIG_RTAI_XENOMAI_SKIN_PSE51_TRUE CONFIG_RTAI_XENOMAI_SKIN_PSE51_FALSE CONFIG_RTAI_XENOMAI_VMLIB_TRUE CONFIG_RTAI_XENOMAI_VMLIB_FALSE CONFIG_RTAI_LAB_TRUE CONFIG_RTAI_LAB_FALSE CONFIG_RTAI_MVM_TRUE CONFIG_RTAI_MVM_FALSE CONFIG_RTAI_TESTSUITE_TRUE CONFIG_RTAI_TESTSUITE_FALSE CONFIG_RTAI_ADEOS_TRUE CONFIG_RTAI_ADEOS_FALSE CONFIG_RTAI_MATH_C99_TRUE CONFIG_RTAI_MATH_C99_FALSE CONFIG_RTAI_COMPAT_TRUE CONFIG_RTAI_COMPAT_FALSE CONFIG_RTAI_DOX_DOC_TRUE CONFIG_RTAI_DOX_DOC_FALSE CONFIG_RTAI_MAINTAINER_TRUE CONFIG_RTAI_MAINTAINER_FALSE CONFIG_RTAI_MAINTAINER_PMA_TRUE CONFIG_RTAI_MAINTAINER_PMA_FALSE CONFIG_RTAI_MAINTAINER_PGM_TRUE CONFIG_RTAI_MAINTAINER_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE EFLTK_DIR COMEDI_DIR RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_BUILTIN_MODLIST RTAI_KMOD_CFLAGS RTAI_KMOD_CXXFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_KMOD_APP_CXXFLAGS RTAI_USER_APP_CFLAGS RTAI_LXRT_LDADD RTAI_FP_CFLAGS RTAI_COMPAT_CPPFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN CONFIG_RTAI_ADDONS_TRUE CONFIG_RTAI_ADDONS_FALSE subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GL_CFLAGS GL_LIBS RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE RTAI_MAYBE_SIMDIR CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_ARM_TRUE CONFIG_ARM_FALSE CONFIG_ARCH_SA1100_TRUE CONFIG_ARCH_SA1100_FALSE CONFIG_ARCH_CLPS711X_TRUE CONFIG_ARCH_CLPS711X_FALSE CONFIG_ARCH_PXA_TRUE CONFIG_ARCH_PXA_FALSE CONFIG_MIPS_TRUE CONFIG_MIPS_FALSE CONFIG_CRIS_TRUE CONFIG_CRIS_FALSE CONFIG_UCLINUX_TRUE CONFIG_UCLINUX_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_SCHED_UP_TRUE CONFIG_RTAI_SCHED_UP_FALSE CONFIG_RTAI_SCHED_MUP_TRUE CONFIG_RTAI_SCHED_MUP_FALSE CONFIG_RTAI_SCHED_SMP_TRUE CONFIG_RTAI_SCHED_SMP_FALSE CONFIG_RTAI_SCHED_LXRT_TRUE CONFIG_RTAI_SCHED_LXRT_FALSE CONFIG_RTAI_XENOMAI_TRUE CONFIG_RTAI_XENOMAI_FALSE CONFIG_RTAI_TRACE_TRUE CONFIG_RTAI_TRACE_FALSE CONFIG_RTAI_MATH_TRUE CONFIG_RTAI_MATH_FALSE CONFIG_RTAI_BITS_TRUE CONFIG_RTAI_BITS_FALSE CONFIG_RTAI_FIFOS_TRUE CONFIG_RTAI_FIFOS_FALSE CONFIG_RTAI_NETRPC_TRUE CONFIG_RTAI_NETRPC_FALSE CONFIG_RTAI_SEM_TRUE CONFIG_RTAI_SEM_FALSE CONFIG_RTAI_MSG_TRUE CONFIG_RTAI_MSG_FALSE CONFIG_RTAI_MBX_TRUE CONFIG_RTAI_MBX_FALSE CONFIG_RTAI_TBX_TRUE CONFIG_RTAI_TBX_FALSE CONFIG_RTAI_MQ_TRUE CONFIG_RTAI_MQ_FALSE CONFIG_RTAI_SHM_TRUE CONFIG_RTAI_SHM_FALSE CONFIG_RTAI_MALLOC_TRUE CONFIG_RTAI_MALLOC_FALSE CONFIG_RTAI_TASKLETS_TRUE CONFIG_RTAI_TASKLETS_FALSE CONFIG_RTAI_USI_TRUE CONFIG_RTAI_USI_FALSE CONFIG_RTAI_WD_TRUE CONFIG_RTAI_WD_FALSE CONFIG_RTAI_LEDS_TRUE CONFIG_RTAI_LEDS_FALSE CONFIG_RTAI_MATH_BUILTIN_TRUE CONFIG_RTAI_MATH_BUILTIN_FALSE CONFIG_RTAI_BITS_BUILTIN_TRUE CONFIG_RTAI_BITS_BUILTIN_FALSE CONFIG_RTAI_FIFOS_BUILTIN_TRUE CONFIG_RTAI_FIFOS_BUILTIN_FALSE CONFIG_RTAI_NETRPC_BUILTIN_TRUE CONFIG_RTAI_NETRPC_BUILTIN_FALSE CONFIG_RTAI_SEM_BUILTIN_TRUE CONFIG_RTAI_SEM_BUILTIN_FALSE CONFIG_RTAI_MSG_BUILTIN_TRUE CONFIG_RTAI_MSG_BUILTIN_FALSE CONFIG_RTAI_MBX_BUILTIN_TRUE CONFIG_RTAI_MBX_BUILTIN_FALSE CONFIG_RTAI_TBX_BUILTIN_TRUE CONFIG_RTAI_TBX_BUILTIN_FALSE CONFIG_RTAI_MQ_BUILTIN_TRUE CONFIG_RTAI_MQ_BUILTIN_FALSE CONFIG_RTAI_SHM_BUILTIN_TRUE CONFIG_RTAI_SHM_BUILTIN_FALSE CONFIG_RTAI_MALLOC_BUILTIN_TRUE CONFIG_RTAI_MALLOC_BUILTIN_FALSE CONFIG_RTAI_TASKLETS_BUILTIN_TRUE CONFIG_RTAI_TASKLETS_BUILTIN_FALSE CONFIG_RTAI_USI_BUILTIN_TRUE CONFIG_RTAI_USI_BUILTIN_FALSE CONFIG_RTAI_LEDS_BUILTIN_TRUE CONFIG_RTAI_LEDS_BUILTIN_FALSE CONFIG_RTAI_COMEDI_LXRT_TRUE CONFIG_RTAI_COMEDI_LXRT_FALSE CONFIG_RTAI_CPLUSPLUS_TRUE CONFIG_RTAI_CPLUSPLUS_FALSE CONFIG_RTAI_SERIAL_TRUE CONFIG_RTAI_SERIAL_FALSE CONFIG_RTAI_XENOMAI_SKIN_PSOS_TRUE CONFIG_RTAI_XENOMAI_SKIN_PSOS_FALSE CONFIG_RTAI_XENOMAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_XENOMAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_XENOMAI_SKIN_VRTX_TRUE CONFIG_RTAI_XENOMAI_SKIN_VRTX_FALSE CONFIG_RTAI_XENOMAI_SKIN_UITRON_TRUE CONFIG_RTAI_XENOMAI_SKIN_UITRON_FALSE CONFIG_RTAI_XENOMAI_SKIN_PSE51_TRUE CONFIG_RTAI_XENOMAI_SKIN_PSE51_FALSE CONFIG_RTAI_XENOMAI_VMLIB_TRUE CONFIG_RTAI_XENOMAI_VMLIB_FALSE CONFIG_RTAI_LAB_TRUE CONFIG_RTAI_LAB_FALSE CONFIG_RTAI_MVM_TRUE CONFIG_RTAI_MVM_FALSE CONFIG_RTAI_TESTSUITE_TRUE CONFIG_RTAI_TESTSUITE_FALSE CONFIG_RTAI_ADEOS_TRUE CONFIG_RTAI_ADEOS_FALSE CONFIG_RTAI_MATH_C99_TRUE CONFIG_RTAI_MATH_C99_FALSE CONFIG_RTAI_COMPAT_TRUE CONFIG_RTAI_COMPAT_FALSE CONFIG_RTAI_DOX_DOC_TRUE CONFIG_RTAI_DOX_DOC_FALSE CONFIG_RTAI_MAINTAINER_TRUE CONFIG_RTAI_MAINTAINER_FALSE CONFIG_RTAI_MAINTAINER_PMA_TRUE CONFIG_RTAI_MAINTAINER_PMA_FALSE CONFIG_RTAI_MAINTAINER_PGM_TRUE CONFIG_RTAI_MAINTAINER_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE EFLTK_DIR COMEDI_DIR RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_BUILTIN_MODLIST RTAI_KMOD_CFLAGS RTAI_KMOD_CXXFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_KMOD_APP_CXXFLAGS RTAI_USER_APP_CFLAGS RTAI_LXRT_LDADD RTAI_FP_CFLAGS RTAI_COMPAT_CPPFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN CONFIG_RTAI_LINUXDIR CONFIG_RTAI_ADDONS_TRUE CONFIG_RTAI_ADDONS_FALSE subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8741,7 +8741,16 @@ if test "${with_linux_dir+set}" = set; then
   withval="$with_linux_dir"
 
 	case "$withval" in
-	"" | y | ye | yes | n | no)
+	"" )
+	    if test x${CONFIG_RTAI_LINUXDIR} = x; then
+		{ { echo "$as_me:$LINENO: error: You must supply an argument to --with-linux-dir." >&5
+echo "$as_me: error: You must supply an argument to --with-linux-dir." >&2;}
+   { (exit 1); exit 1; }; }
+	    else
+		withval=${CONFIG_RTAI_LINUXDIR}
+	    fi
+	  ;;
+	y | ye | yes | n | no)
 	    { { echo "$as_me:$LINENO: error: You must supply an argument to --with-linux-dir." >&5
 echo "$as_me: error: You must supply an argument to --with-linux-dir." >&2;}
    { (exit 1); exit 1; }; }
@@ -8783,7 +8792,9 @@ fi
 RTAI_LINUX_VERSION="$linux_VERSION.$linux_PATCHLEVEL.$linux_SUBLEVEL"
 echo "$as_me:$LINENO: result: $RTAI_LINUX_DIR (kernel ${RTAI_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
 echo "${ECHO_T}$RTAI_LINUX_DIR (kernel ${RTAI_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
-CONFIG_RTAI_LINUXDIR=$RTAI_LINUX_DIR
+if test x${CONFIG_RTAI_LINUXDIR} = x; then
+   CONFIG_RTAI_LINUXDIR=$RTAI_LINUX_DIR
+fi
 
 
 unset CONFIG_RTAI_ADEOS
@@ -13528,6 +13539,8 @@ fi
 
 
 
+
+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ac_config_files="$ac_config_files GNUmakefile rtai-core/GNUmakefile rtai-core/arch/GNUmakefile rtai-core/include/GNUmakefile rtai-core/ipc/GNUmakefile rtai-core/sched/GNUmakefile rtai-core/sched/rtai/GNUmakefile rtai-core/sched/rtai/liblxrt/GNUmakefile rtai-core/sched/xenomai/GNUmakefile rtai-core/sched/xenomai/fusion/GNUmakefile rtai-core/scripts/GNUmakefile rtai-core/scripts/rtai-config rtai-core/scripts/rtai-load rtai-core/arch/i386/GNUmakefile rtai-core/arch/i386/hal/GNUmakefile rtai-core/arch/i386/calibration/GNUmakefile rtai-core/include/asm-i386/GNUmakefile rtai-core/arch/arm/GNUmakefile rtai-core/arch/arm/hal/GNUmakefile rtai-core/include/asm-arm/GNUmakefile rtai-core/arch/ppc/GNUmakefile rtai-core/arch/ppc/hal/GNUmakefile rtai-core/include/asm-ppc/GNUmakefile rtai-core/arch/mips/GNUmakefile rtai-core/arch/mips/hal/GNUmakefile rtai-core/include/asm-mips/GNUmakefile rtai-core/arch/cris/GNUmakefile rtai-core/arch/cris/hal/GNUmakefile rtai-core/include/asm-cris/GNUmakefile rtai-core/ipc/bits/GNUmakefile rtai-core/ipc/fifos/GNUmakefile rtai-core/ipc/netrpc/GNUmakefile rtai-core/ipc/shm/GNUmakefile rtai-core/ipc/sem/GNUmakefile rtai-core/ipc/msg/GNUmakefile rtai-core/ipc/mbx/GNUmakefile rtai-core/ipc/tbx/GNUmakefile rtai-core/ipc/mq/GNUmakefile rtai-core/math/GNUmakefile rtai-core/malloc/GNUmakefile rtai-core/tasklets/GNUmakefile rtai-core/trace/GNUmakefile rtai-core/wd/GNUmakefile rtai-core/usi/GNUmakefile rtai-core/leds/GNUmakefile"
 
 
@@ -15102,6 +15115,7 @@ s,@RTAI_MODULE_EXT@,$RTAI_MODULE_EXT,;t t
 s,@RTAI_KBUILD_ENV@,$RTAI_KBUILD_ENV,;t t
 s,@RTAI_KBUILD_CMD@,$RTAI_KBUILD_CMD,;t t
 s,@RTAI_KBUILD_CLEAN@,$RTAI_KBUILD_CLEAN,;t t
+s,@CONFIG_RTAI_LINUXDIR@,$CONFIG_RTAI_LINUXDIR,;t t
 s,@CONFIG_RTAI_ADDONS_TRUE@,$CONFIG_RTAI_ADDONS_TRUE,;t t
 s,@CONFIG_RTAI_ADDONS_FALSE@,$CONFIG_RTAI_ADDONS_FALSE,;t t
 s,@subdirs@,$subdirs,;t t
