fixed a bug in CONFIG definition (kernel exports both CONFIG_X86 and CONFIG_X86_64)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all rtai-sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GL_CFLAGS GL_LIBS RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE RTAI_MAYBE_SIMDIR CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_X86_64_TRUE CONFIG_X86_64_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_ARM_TRUE CONFIG_ARM_FALSE CONFIG_ARCH_EP9301_TRUE CONFIG_ARCH_EP9301_FALSE CONFIG_ARCH_PXA_TRUE CONFIG_ARCH_PXA_FALSE CONFIG_UCLINUX_TRUE CONFIG_UCLINUX_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_SCHED_UP_TRUE CONFIG_RTAI_SCHED_UP_FALSE CONFIG_RTAI_SCHED_MUP_TRUE CONFIG_RTAI_SCHED_MUP_FALSE CONFIG_RTAI_SCHED_SMP_TRUE CONFIG_RTAI_SCHED_SMP_FALSE CONFIG_RTAI_SCHED_LXRT_TRUE CONFIG_RTAI_SCHED_LXRT_FALSE CONFIG_RTAI_TRACE_TRUE CONFIG_RTAI_TRACE_FALSE CONFIG_RTAI_MATH_TRUE CONFIG_RTAI_MATH_FALSE CONFIG_RTAI_BITS_TRUE CONFIG_RTAI_BITS_FALSE CONFIG_RTAI_FIFOS_TRUE CONFIG_RTAI_FIFOS_FALSE CONFIG_RTAI_NETRPC_TRUE CONFIG_RTAI_NETRPC_FALSE CONFIG_RTAI_SEM_TRUE CONFIG_RTAI_SEM_FALSE CONFIG_RTAI_MSG_TRUE CONFIG_RTAI_MSG_FALSE CONFIG_RTAI_MBX_TRUE CONFIG_RTAI_MBX_FALSE CONFIG_RTAI_TBX_TRUE CONFIG_RTAI_TBX_FALSE CONFIG_RTAI_MQ_TRUE CONFIG_RTAI_MQ_FALSE CONFIG_RTAI_SHM_TRUE CONFIG_RTAI_SHM_FALSE CONFIG_RTAI_MALLOC_TRUE CONFIG_RTAI_MALLOC_FALSE CONFIG_RTAI_TASKLETS_TRUE CONFIG_RTAI_TASKLETS_FALSE CONFIG_RTAI_USI_TRUE CONFIG_RTAI_USI_FALSE CONFIG_RTAI_WD_TRUE CONFIG_RTAI_WD_FALSE CONFIG_RTAI_LEDS_TRUE CONFIG_RTAI_LEDS_FALSE CONFIG_RTAI_MATH_BUILTIN_TRUE CONFIG_RTAI_MATH_BUILTIN_FALSE CONFIG_RTAI_BITS_BUILTIN_TRUE CONFIG_RTAI_BITS_BUILTIN_FALSE CONFIG_RTAI_FIFOS_BUILTIN_TRUE CONFIG_RTAI_FIFOS_BUILTIN_FALSE CONFIG_RTAI_NETRPC_BUILTIN_TRUE CONFIG_RTAI_NETRPC_BUILTIN_FALSE CONFIG_RTAI_SEM_BUILTIN_TRUE CONFIG_RTAI_SEM_BUILTIN_FALSE CONFIG_RTAI_MSG_BUILTIN_TRUE CONFIG_RTAI_MSG_BUILTIN_FALSE CONFIG_RTAI_MBX_BUILTIN_TRUE CONFIG_RTAI_MBX_BUILTIN_FALSE CONFIG_RTAI_TBX_BUILTIN_TRUE CONFIG_RTAI_TBX_BUILTIN_FALSE CONFIG_RTAI_MQ_BUILTIN_TRUE CONFIG_RTAI_MQ_BUILTIN_FALSE CONFIG_RTAI_SHM_BUILTIN_TRUE CONFIG_RTAI_SHM_BUILTIN_FALSE CONFIG_RTAI_MALLOC_BUILTIN_TRUE CONFIG_RTAI_MALLOC_BUILTIN_FALSE CONFIG_RTAI_TASKLETS_BUILTIN_TRUE CONFIG_RTAI_TASKLETS_BUILTIN_FALSE CONFIG_RTAI_USI_BUILTIN_TRUE CONFIG_RTAI_USI_BUILTIN_FALSE CONFIG_RTAI_LEDS_BUILTIN_TRUE CONFIG_RTAI_LEDS_BUILTIN_FALSE CONFIG_RTAI_COMEDI_LXRT_TRUE CONFIG_RTAI_COMEDI_LXRT_FALSE CONFIG_RTAI_CPLUSPLUS_TRUE CONFIG_RTAI_CPLUSPLUS_FALSE CONFIG_RTAI_SERIAL_TRUE CONFIG_RTAI_SERIAL_FALSE CONFIG_RTAI_LAB_TRUE CONFIG_RTAI_LAB_FALSE CONFIG_RTAI_MVM_TRUE CONFIG_RTAI_MVM_FALSE CONFIG_RTAI_TESTSUITE_TRUE CONFIG_RTAI_TESTSUITE_FALSE CONFIG_RTAI_ADEOS_TRUE CONFIG_RTAI_ADEOS_FALSE CONFIG_RTAI_MATH_C99_TRUE CONFIG_RTAI_MATH_C99_FALSE CONFIG_RTAI_DOX_DOC_TRUE CONFIG_RTAI_DOX_DOC_FALSE CONFIG_RTAI_MAINTAINER_TRUE CONFIG_RTAI_MAINTAINER_FALSE CONFIG_RTAI_MAINTAINER_PMA_TRUE CONFIG_RTAI_MAINTAINER_PMA_FALSE CONFIG_RTAI_MAINTAINER_PGM_TRUE CONFIG_RTAI_MAINTAINER_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE EFLTK_DIR COMEDI_DIR RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_BUILTIN_MODLIST RTAI_KMOD_CFLAGS RTAI_KMOD_CXXFLAGS RTAI_COMPAT_CPPFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_KMOD_APP_CXXFLAGS RTAI_USER_APP_CFLAGS RTAI_LXRT_LDADD RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN CONFIG_RTAI_LINUXDIR CONFIG_RTAI_ADDONS_TRUE CONFIG_RTAI_ADDONS_FALSE subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GL_CFLAGS GL_LIBS RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE RTAI_MAYBE_SIMDIR CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE CONFIG_X86_64_TRUE CONFIG_X86_64_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_ARM_TRUE CONFIG_ARM_FALSE CONFIG_ARCH_EP9301_TRUE CONFIG_ARCH_EP9301_FALSE CONFIG_ARCH_PXA_TRUE CONFIG_ARCH_PXA_FALSE CONFIG_UCLINUX_TRUE CONFIG_UCLINUX_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_SCHED_UP_TRUE CONFIG_RTAI_SCHED_UP_FALSE CONFIG_RTAI_SCHED_MUP_TRUE CONFIG_RTAI_SCHED_MUP_FALSE CONFIG_RTAI_SCHED_SMP_TRUE CONFIG_RTAI_SCHED_SMP_FALSE CONFIG_RTAI_SCHED_LXRT_TRUE CONFIG_RTAI_SCHED_LXRT_FALSE CONFIG_RTAI_TRACE_TRUE CONFIG_RTAI_TRACE_FALSE CONFIG_RTAI_MATH_TRUE CONFIG_RTAI_MATH_FALSE CONFIG_RTAI_BITS_TRUE CONFIG_RTAI_BITS_FALSE CONFIG_RTAI_FIFOS_TRUE CONFIG_RTAI_FIFOS_FALSE CONFIG_RTAI_NETRPC_TRUE CONFIG_RTAI_NETRPC_FALSE CONFIG_RTAI_SEM_TRUE CONFIG_RTAI_SEM_FALSE CONFIG_RTAI_MSG_TRUE CONFIG_RTAI_MSG_FALSE CONFIG_RTAI_MBX_TRUE CONFIG_RTAI_MBX_FALSE CONFIG_RTAI_TBX_TRUE CONFIG_RTAI_TBX_FALSE CONFIG_RTAI_MQ_TRUE CONFIG_RTAI_MQ_FALSE CONFIG_RTAI_SHM_TRUE CONFIG_RTAI_SHM_FALSE CONFIG_RTAI_MALLOC_TRUE CONFIG_RTAI_MALLOC_FALSE CONFIG_RTAI_TASKLETS_TRUE CONFIG_RTAI_TASKLETS_FALSE CONFIG_RTAI_USI_TRUE CONFIG_RTAI_USI_FALSE CONFIG_RTAI_WD_TRUE CONFIG_RTAI_WD_FALSE CONFIG_RTAI_LEDS_TRUE CONFIG_RTAI_LEDS_FALSE CONFIG_RTAI_MATH_BUILTIN_TRUE CONFIG_RTAI_MATH_BUILTIN_FALSE CONFIG_RTAI_BITS_BUILTIN_TRUE CONFIG_RTAI_BITS_BUILTIN_FALSE CONFIG_RTAI_FIFOS_BUILTIN_TRUE CONFIG_RTAI_FIFOS_BUILTIN_FALSE CONFIG_RTAI_NETRPC_BUILTIN_TRUE CONFIG_RTAI_NETRPC_BUILTIN_FALSE CONFIG_RTAI_SEM_BUILTIN_TRUE CONFIG_RTAI_SEM_BUILTIN_FALSE CONFIG_RTAI_MSG_BUILTIN_TRUE CONFIG_RTAI_MSG_BUILTIN_FALSE CONFIG_RTAI_MBX_BUILTIN_TRUE CONFIG_RTAI_MBX_BUILTIN_FALSE CONFIG_RTAI_TBX_BUILTIN_TRUE CONFIG_RTAI_TBX_BUILTIN_FALSE CONFIG_RTAI_MQ_BUILTIN_TRUE CONFIG_RTAI_MQ_BUILTIN_FALSE CONFIG_RTAI_SHM_BUILTIN_TRUE CONFIG_RTAI_SHM_BUILTIN_FALSE CONFIG_RTAI_MALLOC_BUILTIN_TRUE CONFIG_RTAI_MALLOC_BUILTIN_FALSE CONFIG_RTAI_TASKLETS_BUILTIN_TRUE CONFIG_RTAI_TASKLETS_BUILTIN_FALSE CONFIG_RTAI_USI_BUILTIN_TRUE CONFIG_RTAI_USI_BUILTIN_FALSE CONFIG_RTAI_LEDS_BUILTIN_TRUE CONFIG_RTAI_LEDS_BUILTIN_FALSE CONFIG_RTAI_COMEDI_LXRT_TRUE CONFIG_RTAI_COMEDI_LXRT_FALSE CONFIG_RTAI_CPLUSPLUS_TRUE CONFIG_RTAI_CPLUSPLUS_FALSE CONFIG_RTAI_SERIAL_TRUE CONFIG_RTAI_SERIAL_FALSE CONFIG_RTAI_LAB_TRUE CONFIG_RTAI_LAB_FALSE CONFIG_RTAI_MVM_TRUE CONFIG_RTAI_MVM_FALSE CONFIG_RTAI_TESTSUITE_TRUE CONFIG_RTAI_TESTSUITE_FALSE CONFIG_RTAI_ADEOS_TRUE CONFIG_RTAI_ADEOS_FALSE CONFIG_RTAI_MATH_C99_TRUE CONFIG_RTAI_MATH_C99_FALSE CONFIG_RTAI_DOX_DOC_TRUE CONFIG_RTAI_DOX_DOC_FALSE CONFIG_RTAI_MAINTAINER_TRUE CONFIG_RTAI_MAINTAINER_FALSE CONFIG_RTAI_MAINTAINER_PMA_TRUE CONFIG_RTAI_MAINTAINER_PMA_FALSE CONFIG_RTAI_MAINTAINER_PGM_TRUE CONFIG_RTAI_MAINTAINER_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE EFLTK_DIR COMEDI_DIR RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_BUILTIN_MODLIST RTAI_KMOD_CFLAGS RTAI_KMOD_CXXFLAGS RTAI_COMPAT_CPPFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_KMOD_APP_CXXFLAGS RTAI_USER_APP_CFLAGS RTAI_LXRT_LDADD RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN CONFIG_RTAI_LINUXDIR CONFIG_RTAI_ADDONS_TRUE CONFIG_RTAI_ADDONS_FALSE subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19297,9 +19297,11 @@ case "$host" in
 	arch_supports_rtailab=y
 	wanted_kernel_arch=CONFIG_X86
         ;;
- x86_64-*)
-	RTAI_TARGET_ARCH=x86_64
-	wanted_kernel_arch=CONFIG_X86_64
+ x86_64*-*)
+        RTAI_TARGET_ARCH=x86_64
+        arch_supports_lxrt=y
+        arch_supports_rtailab=n
+        wanted_kernel_arch=CONFIG_X86_64
         ;;
  arm-*)
 	RTAI_TARGET_ARCH=arm
@@ -19513,6 +19515,14 @@ fi
 if test x${CONFIG_MODULES} = x ; then
   { { echo "$as_me:$LINENO: error: Please set CONFIG_MODULES for $RTAI_LINUX_DIR and rebuild your kernel" >&5
 echo "$as_me: error: Please set CONFIG_MODULES for $RTAI_LINUX_DIR and rebuild your kernel" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test x${CONFIG_REGPARM} = xy ; then
+  { { echo "$as_me:$LINENO: error: Please unset CONFIG_REGPARM for $RTAI_LINUX_DIR and
+rebuild your kernel" >&5
+echo "$as_me: error: Please unset CONFIG_REGPARM for $RTAI_LINUX_DIR and
+rebuild your kernel" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -23438,22 +23448,22 @@ fi
 
 
 
-if test "$CONFIG_X86" = y -a "$CONFIG_X86_64" = n; then
-  CONFIG_X86_TRUE=
-  CONFIG_X86_FALSE='#'
-else
-  CONFIG_X86_TRUE='#'
-  CONFIG_X86_FALSE=
-fi
-
-
-
 if test "$CONFIG_X86_64" = y; then
   CONFIG_X86_64_TRUE=
   CONFIG_X86_64_FALSE='#'
 else
   CONFIG_X86_64_TRUE='#'
   CONFIG_X86_64_FALSE=
+fi
+
+
+
+if test "$CONFIG_X86" = y -a "x$CONFIG_X86_64" != xy; then
+  CONFIG_X86_TRUE=
+  CONFIG_X86_FALSE='#'
+else
+  CONFIG_X86_TRUE='#'
+  CONFIG_X86_FALSE=
 fi
 
 
@@ -24052,6 +24062,17 @@ case $RTAI_TARGET_ARCH in
 	   RTAI_FP_CFLAGS="-ffast-math -msoft-float"
 	fi
         ;;
+ x86_64)
+        RTAI_TARGET_SUBARCH=
+        RTAI_KMOD_CXXFLAGS="$RTAI_KMOD_CFLAGS -fno-rtti -fno-exceptions -fno-strength-reduce -pipe -fno-omit-frame-pointer"
+        RTAI_USER_CFLAGS="$RTAI_USER_CFLAGS -Wall -Wstrict-prototypes -pipe"
+        if test x$CONFIG_RTAI_FPU_SUPPORT = xy; then
+           RTAI_FP_CFLAGS="-ffast-math -mhard-float"
+        else
+           RTAI_FP_CFLAGS="-ffast-math -msoft-float"
+        fi
+        ;;
+
  arm)
 	if test "$CONFIG_ARCH_EP9301" = y; then
                RTAI_TARGET_SUBARCH=ep9301
@@ -24217,7 +24238,7 @@ fi
 
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files GNUmakefile base/GNUmakefile base/arch/GNUmakefile base/include/GNUmakefile base/ipc/GNUmakefile base/sched/GNUmakefile base/sched/liblxrt/GNUmakefile base/scripts/GNUmakefile base/scripts/rtai-config base/scripts/rtai-load base/arch/i386/GNUmakefile base/arch/i386/hal/GNUmakefile base/arch/i386/calibration/GNUmakefile base/include/asm-i386/GNUmakefile base/arch/x86_64/GNUmakefile base/arch/x86_64/calibration/GNUmakefile base/arch/x86_64/hal/GNUmakefile base/include/asm-x86_64/GNUmakefile base/arch/arm/GNUmakefile base/arch/arm/hal/GNUmakefile base/include/asm-arm/GNUmakefile base/arch/ppc/GNUmakefile base/arch/ppc/hal/GNUmakefile base/include/asm-ppc/GNUmakefile base/ipc/bits/GNUmakefile base/ipc/fifos/GNUmakefile base/ipc/netrpc/GNUmakefile base/ipc/shm/GNUmakefile base/ipc/sem/GNUmakefile base/ipc/msg/GNUmakefile base/ipc/mbx/GNUmakefile base/ipc/tbx/GNUmakefile base/ipc/mq/GNUmakefile base/math/GNUmakefile base/malloc/GNUmakefile base/tasklets/GNUmakefile base/trace/GNUmakefile base/wd/GNUmakefile base/usi/GNUmakefile base/leds/GNUmakefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files GNUmakefile base/GNUmakefile base/arch/GNUmakefile base/include/GNUmakefile base/ipc/GNUmakefile base/sched/GNUmakefile base/sched/liblxrt/GNUmakefile base/scripts/GNUmakefile base/scripts/rtai-config base/scripts/rtai-load base/arch/i386/GNUmakefile base/arch/i386/hal/GNUmakefile base/arch/i386/calibration/GNUmakefile base/include/asm-i386/GNUmakefile base/arch/x86_64/GNUmakefile base/arch/x86_64/hal/GNUmakefile base/arch/x86_64/calibration/GNUmakefile base/include/asm-x86_64/GNUmakefile base/arch/arm/GNUmakefile base/arch/arm/hal/GNUmakefile base/include/asm-arm/GNUmakefile base/arch/ppc/GNUmakefile base/arch/ppc/hal/GNUmakefile base/include/asm-ppc/GNUmakefile base/ipc/bits/GNUmakefile base/ipc/fifos/GNUmakefile base/ipc/netrpc/GNUmakefile base/ipc/shm/GNUmakefile base/ipc/sem/GNUmakefile base/ipc/msg/GNUmakefile base/ipc/mbx/GNUmakefile base/ipc/tbx/GNUmakefile base/ipc/mq/GNUmakefile base/math/GNUmakefile base/malloc/GNUmakefile base/tasklets/GNUmakefile base/trace/GNUmakefile base/wd/GNUmakefile base/usi/GNUmakefile base/leds/GNUmakefile"
 
 
 build_addons=$CONFIG_RTAI_CPLUSPLUS$CONFIG_RTAI_SERIAL$CONFIG_RTAI_COMEDI_LXRT
@@ -24419,17 +24440,17 @@ echo "$as_me: error: conditional \"CONFIG_KBUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${CONFIG_X86_TRUE}" && test -z "${CONFIG_X86_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_X86\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"CONFIG_X86\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${CONFIG_X86_64_TRUE}" && test -z "${CONFIG_X86_64_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_X86_64\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_X86_64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_X86_TRUE}" && test -z "${CONFIG_X86_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_X86\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_X86\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25273,8 +25294,8 @@ do
   "base/arch/i386/calibration/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/i386/calibration/GNUmakefile" ;;
   "base/include/asm-i386/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/include/asm-i386/GNUmakefile" ;;
   "base/arch/x86_64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/x86_64/GNUmakefile" ;;
-  "base/arch/x86_64/calibration/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/x86_64/calibration/GNUmakefile" ;;
   "base/arch/x86_64/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/x86_64/hal/GNUmakefile" ;;
+  "base/arch/x86_64/calibration/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/x86_64/calibration/GNUmakefile" ;;
   "base/include/asm-x86_64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/include/asm-x86_64/GNUmakefile" ;;
   "base/arch/arm/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/arm/GNUmakefile" ;;
   "base/arch/arm/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES base/arch/arm/hal/GNUmakefile" ;;
@@ -25538,10 +25559,10 @@ s,@CONFIG_X86_LOCAL_APIC_TRUE@,$CONFIG_X86_LOCAL_APIC_TRUE,;t t
 s,@CONFIG_X86_LOCAL_APIC_FALSE@,$CONFIG_X86_LOCAL_APIC_FALSE,;t t
 s,@CONFIG_KBUILD_TRUE@,$CONFIG_KBUILD_TRUE,;t t
 s,@CONFIG_KBUILD_FALSE@,$CONFIG_KBUILD_FALSE,;t t
-s,@CONFIG_X86_TRUE@,$CONFIG_X86_TRUE,;t t
-s,@CONFIG_X86_FALSE@,$CONFIG_X86_FALSE,;t t
 s,@CONFIG_X86_64_TRUE@,$CONFIG_X86_64_TRUE,;t t
 s,@CONFIG_X86_64_FALSE@,$CONFIG_X86_64_FALSE,;t t
+s,@CONFIG_X86_TRUE@,$CONFIG_X86_TRUE,;t t
+s,@CONFIG_X86_FALSE@,$CONFIG_X86_FALSE,;t t
 s,@CONFIG_PPC_TRUE@,$CONFIG_PPC_TRUE,;t t
 s,@CONFIG_PPC_FALSE@,$CONFIG_PPC_FALSE,;t t
 s,@CONFIG_ARM_TRUE@,$CONFIG_ARM_TRUE,;t t
