Allow for setting the system heap size using the config interface

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -1052,6 +1052,8 @@ Optional Features:
   --enable-nucleus-pipe   Enable message pipe support in nucleus
   --enable-nucleus-pipe-nrdev
                           Set maximum number of pipe devices
+  --enable-nucleus-heap-size
+                          Set size of the system heap (Kb)
   --enable-percpu-timer   Enable per-cpu timer support in nucleus
   --enable-nucleus-debug  Enable debug support in nucleus
   --enable-nucleus-watchdog
@@ -3819,7 +3821,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3822 "configure"' > conftest.$ac_ext
+  echo '#line 3824 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5391,7 +5393,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5394:" \
+echo "$as_me:5396:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6441,11 +6443,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6444: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6446: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6448: \$? = $ac_status" >&5
+   echo "$as_me:6450: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6684,11 +6686,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6687: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6689: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6691: \$? = $ac_status" >&5
+   echo "$as_me:6693: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6744,11 +6746,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6747: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6749: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6751: \$? = $ac_status" >&5
+   echo "$as_me:6753: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8929,7 +8931,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8932 "configure"
+#line 8934 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9027,7 +9029,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9030 "configure"
+#line 9032 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11216,11 +11218,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11219: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11221: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11223: \$? = $ac_status" >&5
+   echo "$as_me:11225: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11276,11 +11278,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11279: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11281: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11283: \$? = $ac_status" >&5
+   echo "$as_me:11285: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12637,7 +12639,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12640 "configure"
+#line 12642 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12735,7 +12737,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12738 "configure"
+#line 12740 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13572,11 +13574,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13575: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13577: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13579: \$? = $ac_status" >&5
+   echo "$as_me:13581: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13632,11 +13634,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13635: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13637: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13639: \$? = $ac_status" >&5
+   echo "$as_me:13641: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15667,11 +15669,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15670: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15672: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15674: \$? = $ac_status" >&5
+   echo "$as_me:15676: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15910,11 +15912,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15913: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15915: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15917: \$? = $ac_status" >&5
+   echo "$as_me:15919: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15970,11 +15972,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15973: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15975: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15977: \$? = $ac_status" >&5
+   echo "$as_me:15979: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18155,7 +18157,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18158 "configure"
+#line 18160 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18253,7 +18255,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18256 "configure"
+#line 18258 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19875,6 +19877,25 @@ else
   RTAI_PIPE_NRDEV=-1
 fi
 
+echo "$as_me:$LINENO: checking for the system heap size" >&5
+echo $ECHO_N "checking for the system heap size... $ECHO_C" >&6
+# Check whether --enable-nucleus-heap-size or --disable-nucleus-heap-size was given.
+if test "${enable_nucleus_heap_size+set}" = set; then
+  enableval="$enable_nucleus_heap_size"
+  case "$enableval" in
+	[0-9]*) CONFIG_RTAI_OPT_SYS_HEAPSZ=$enableval ;;
+	*) { { echo "$as_me:$LINENO: error: Bad argument to option: --enable-nucleus-heap-size=<number>" >&5
+echo "$as_me: error: Bad argument to option: --enable-nucleus-heap-size=<number>" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+fi;
+if test x$CONFIG_RTAI_OPT_SYS_HEAPSZ = x ; then
+  # Use a reasonable default if unset
+  CONFIG_RTAI_OPT_SYS_HEAPSZ=128
+fi
+echo "$as_me:$LINENO: result: $CONFIG_RTAI_OPT_SYS_HEAPSZ Kbytes" >&5
+echo "${ECHO_T}$CONFIG_RTAI_OPT_SYS_HEAPSZ Kbytes" >&6
+
 echo "$as_me:$LINENO: checking for per-cpu timer list" >&5
 echo $ECHO_N "checking for per-cpu timer list... $ECHO_C" >&6
 # Check whether --enable-percpu-timer or --disable-percpu-timer was given.
@@ -21376,6 +21397,11 @@ else
   CONFIG_RTAI_OPT_PIPE_TRUE='#'
   CONFIG_RTAI_OPT_PIPE_FALSE=
 fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define CONFIG_RTAI_OPT_SYS_HEAPSZ $CONFIG_RTAI_OPT_SYS_HEAPSZ
+_ACEOF
 
 
 
