Add tracing module & have distcheck target working

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN CONFIG_RTAI_LINUXDIR subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CONFIG_RTAI_OPT_TRACES_TRUE CONFIG_RTAI_OPT_TRACES_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN CONFIG_RTAI_LINUXDIR subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1042,6 +1042,7 @@ Optional Features:
  --enable-aperiodic-timer		Enable aperiodic timer support
  --enable-module-debug	Enable debug information in kernel modules
  --enable-user-debug	Enable debug information in user-space programs
+ --enable-traces       Enable trace module
  --enable-timer-latency	Set timer tuning latency
  --enable-sched-latency	Set scheduling latency
  --enable-sim		Build RTAI simulator (MVM)
@@ -4701,7 +4702,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4704 "configure"' > conftest.$ac_ext
+  echo '#line 4705 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5230,7 +5231,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5233: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5234: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7062,7 +7063,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7065 "configure"
+#line 7066 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7160,7 +7161,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7163 "configure"
+#line 7164 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8263,10 +8264,14 @@ echo "$as_me: error: You must supply an argument to --with-linux-dir." >&2;}
 fi;
 
 if test x${RTAI_LINUX_DIR} = x; then
-   echo
-   { { echo "$as_me:$LINENO: error: Linux kernel tree not specified -- use --with-linux-dir" >&5
+   if test -f /lib/modules/`uname -r`/build/Makefile; then
+        RTAI_LINUX_DIR=/lib/modules/`uname -r`/build
+   else
+        echo
+        { { echo "$as_me:$LINENO: error: Linux kernel tree not specified -- use --with-linux-dir" >&5
 echo "$as_me: error: Linux kernel tree not specified -- use --with-linux-dir" >&2;}
    { (exit 1); exit 1; }; }
+   fi
 fi
 
 if test \! -r ${RTAI_LINUX_DIR}/Makefile; then
@@ -8648,6 +8653,19 @@ if test "${enable_user_debug+set}" = set; then
 fi;
 echo "$as_me:$LINENO: result: ${CONFIG_RTAI_OPT_USYMS:-no}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_OPT_USYMS:-no}" >&6
+
+echo "$as_me:$LINENO: checking for trace module" >&5
+echo $ECHO_N "checking for trace module... $ECHO_C" >&6
+# Check whether --enable-traces or --disable-traces was given.
+if test "${enable_traces+set}" = set; then
+  enableval="$enable_traces"
+  case "$enableval" in
+        y | yes) CONFIG_RTAI_OPT_TRACES=y ;;
+        *) unset CONFIG_RTAI_OPT_TRACES ;;
+        esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTAI_OPT_TRACES:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTAI_OPT_TRACES:-no}" >&6
 
 case $RTAI_TARGET_ARCH in
  i386)
@@ -9258,6 +9276,11 @@ cat >>confdefs.h <<\_ACEOF
 #define CONFIG_RTAI_OPT_TIMESTAMPS 1
 _ACEOF
 
+test x$CONFIG_RTAI_OPT_TRACES = xy &&
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTAI_OPT_TRACES 1
+_ACEOF
+
 
 test \! x$CONFIG_RTAI_OPT_NATIVE_REGISTRY = x &&
 cat >>confdefs.h <<\_ACEOF
@@ -9538,6 +9561,17 @@ fi
 
 
 
+
+if test "$CONFIG_RTAI_OPT_TRACES" = y; then
+  CONFIG_RTAI_OPT_TRACES_TRUE=
+  CONFIG_RTAI_OPT_TRACES_FALSE='#'
+else
+  CONFIG_RTAI_OPT_TRACES_TRUE='#'
+  CONFIG_RTAI_OPT_TRACES_FALSE=
+fi
+
+
+
 RTAI_MODULE_EXT=.ko
 RTAI_KBUILD_ENV='src2obj = $(patsubst %.$(1),%.o,$(filter %.$(1),$(call notdir,$(2))))'
 RTAI_KBUILD_CMD="@for src in \$^; do if test \\! -r \`basename \$\$src\`; then \$(LN_S) \$\$src; fi; done; \
@@ -9546,6 +9580,7 @@ RTAI_KBUILD_CMD="@for src in \$^; do if test \\! -r \`basename \$\$src\`; then \
 		    rtai_objs='\$(call src2obj,c,\$^) \$(call src2obj,S,\$^) \$(call src2obj,cc,\$^) \$(call src2obj,cpp,\$^)' rtai_target=\$(basename \$@)"
 
 RTAI_KBUILD_CLEAN='rm -f *.ko *.mod.c .*.cmd *.o'
+RTAI_KBUILD_DISTCLEAN='rm -Rf .tmp_versions'
 
 echo "$as_me:$LINENO: checking for kernel module extension" >&5
 echo $ECHO_N "checking for kernel module extension... $ECHO_C" >&6
@@ -9618,6 +9653,7 @@ fi
           ac_config_links="$ac_config_links skins/vxworks/Makefile:skins/vxworks/Makefile.kbuild"
 
           ac_config_links="$ac_config_links testsuite/klatency/Makefile:testsuite/klatency/Makefile.kbuild"
+
 
 
 
@@ -9946,6 +9982,13 @@ if test -z "${CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE}" && test -z "${CONFIG_RTAI_O
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_OLD_FASHIONED_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTAI_OLD_FASHIONED_BUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTAI_OPT_TRACES_TRUE}" && test -z "${CONFIG_RTAI_OPT_TRACES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_OPT_TRACES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTAI_OPT_TRACES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10655,6 +10698,8 @@ s,@CONFIG_RTAI_MAINT_PGM_TRUE@,$CONFIG_RTAI_MAINT_PGM_TRUE,;t t
 s,@CONFIG_RTAI_MAINT_PGM_FALSE@,$CONFIG_RTAI_MAINT_PGM_FALSE,;t t
 s,@CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE@,$CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE,;t t
 s,@CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE@,$CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE,;t t
+s,@CONFIG_RTAI_OPT_TRACES_TRUE@,$CONFIG_RTAI_OPT_TRACES_TRUE,;t t
+s,@CONFIG_RTAI_OPT_TRACES_FALSE@,$CONFIG_RTAI_OPT_TRACES_FALSE,;t t
 s,@CROSS_COMPILE@,$CROSS_COMPILE,;t t
 s,@DOXYGEN_SHOW_INCLUDE_FILES@,$DOXYGEN_SHOW_INCLUDE_FILES,;t t
 s,@LATEX_BATCHMODE@,$LATEX_BATCHMODE,;t t
@@ -10675,6 +10720,7 @@ s,@RTAI_MODULE_EXT@,$RTAI_MODULE_EXT,;t t
 s,@RTAI_KBUILD_ENV@,$RTAI_KBUILD_ENV,;t t
 s,@RTAI_KBUILD_CMD@,$RTAI_KBUILD_CMD,;t t
 s,@RTAI_KBUILD_CLEAN@,$RTAI_KBUILD_CLEAN,;t t
+s,@RTAI_KBUILD_DISTCLEAN@,$RTAI_KBUILD_DISTCLEAN,;t t
 s,@CONFIG_RTAI_LINUXDIR@,$CONFIG_RTAI_LINUXDIR,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
