Export module symbols to a central repository

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT CONFIG_RTAI_HW_SMI_DETECT_TRUE CONFIG_RTAI_HW_SMI_DETECT_FALSE RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_PPC64_TRUE CONFIG_PPC64_FALSE CONFIG_IA64_TRUE CONFIG_IA64_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_LTT_TRUE CONFIG_LTT_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_OPT_FUSION_TRUE CONFIG_RTAI_OPT_FUSION_FALSE CONFIG_RTAI_OPT_PIPE_TRUE CONFIG_RTAI_OPT_PIPE_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_SKIN_RTDM_TRUE CONFIG_RTAI_SKIN_RTDM_FALSE CONFIG_RTAI_SKIN_COMPAT_TRUE CONFIG_RTAI_SKIN_COMPAT_FALSE CONFIG_RTAI_OPT_UVM_TRUE CONFIG_RTAI_OPT_UVM_FALSE CONFIG_RTAI_DRIVERS_16550A_TRUE CONFIG_RTAI_DRIVERS_16550A_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE CONFIG_RTAI_OPT_NATIVE_HEAP_TRUE CONFIG_RTAI_OPT_NATIVE_HEAP_FALSE CONFIG_RTAI_OPT_NATIVE_ALARM_TRUE CONFIG_RTAI_OPT_NATIVE_ALARM_FALSE CONFIG_RTAI_OPT_NATIVE_INTR_TRUE CONFIG_RTAI_OPT_NATIVE_INTR_FALSE CONFIG_RTAI_OPT_COMPAT_SEM_TRUE CONFIG_RTAI_OPT_COMPAT_SEM_FALSE CONFIG_RTAI_OPT_COMPAT_FIFO_TRUE CONFIG_RTAI_OPT_COMPAT_FIFO_FALSE CONFIG_RTAI_OPT_COMPAT_SHM_TRUE CONFIG_RTAI_OPT_COMPAT_SHM_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN RTAI_PIPE_NRDEV subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT CONFIG_RTAI_HW_SMI_DETECT_TRUE CONFIG_RTAI_HW_SMI_DETECT_FALSE RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_PPC64_TRUE CONFIG_PPC64_FALSE CONFIG_IA64_TRUE CONFIG_IA64_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_LTT_TRUE CONFIG_LTT_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_OPT_FUSION_TRUE CONFIG_RTAI_OPT_FUSION_FALSE CONFIG_RTAI_OPT_PIPE_TRUE CONFIG_RTAI_OPT_PIPE_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_SKIN_RTDM_TRUE CONFIG_RTAI_SKIN_RTDM_FALSE CONFIG_RTAI_SKIN_COMPAT_TRUE CONFIG_RTAI_SKIN_COMPAT_FALSE CONFIG_RTAI_OPT_UVM_TRUE CONFIG_RTAI_OPT_UVM_FALSE CONFIG_RTAI_DRIVERS_16550A_TRUE CONFIG_RTAI_DRIVERS_16550A_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE CONFIG_RTAI_OPT_NATIVE_HEAP_TRUE CONFIG_RTAI_OPT_NATIVE_HEAP_FALSE CONFIG_RTAI_OPT_NATIVE_ALARM_TRUE CONFIG_RTAI_OPT_NATIVE_ALARM_FALSE CONFIG_RTAI_OPT_NATIVE_INTR_TRUE CONFIG_RTAI_OPT_NATIVE_INTR_FALSE CONFIG_RTAI_OPT_COMPAT_SEM_TRUE CONFIG_RTAI_OPT_COMPAT_SEM_FALSE CONFIG_RTAI_OPT_COMPAT_FIFO_TRUE CONFIG_RTAI_OPT_COMPAT_FIFO_FALSE CONFIG_RTAI_OPT_COMPAT_SHM_TRUE CONFIG_RTAI_OPT_COMPAT_SHM_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_SYMBOL_DIR RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN RTAI_PIPE_NRDEV subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19652,7 +19652,10 @@ echo "$as_me: error: You must supply an argument to --with-module-dir." >&2;}
 
 fi;
 
-if test "$srcdir" = `pwd`; then
+top_builddir=`pwd`
+
+
+if test "$srcdir" = $top_builddir; then
    CONFIG_RTAI_OLD_FASHIONED_BUILD=y
 else
    CONFIG_RTAI_OLD_FASHIONED_BUILD=
@@ -19667,7 +19670,8 @@ fi
 
 echo "$as_me:$LINENO: result: $RTAI_MODULE_DIR" >&5
 echo "${ECHO_T}$RTAI_MODULE_DIR" >&6
-CONFIG_RTAI_MODULE_DIR=$RTAI_MODULE_DIR
+
+RTAI_SYMBOL_DIR='${exec_prefix}/symbols'
 
 
 echo "$as_me:$LINENO: checking for Linux build tree" >&5
@@ -19760,8 +19764,13 @@ if test -r $RTAI_LINUX_SRCDIR/include/linux/ipipe.h; then
    echo "$as_me:$LINENO: result: I-pipe ($v)" >&5
 echo "${ECHO_T}I-pipe ($v)" >&6
    if test x${CONFIG_IPIPE} = x; then
-      { { echo "$as_me:$LINENO: error: Please activate the I-pipe support in $RTAI_LINUX_DIR and rebuild your kernel" >&5
-echo "$as_me: error: Please activate the I-pipe support in $RTAI_LINUX_DIR and rebuild your kernel" >&2;}
+      { { echo "$as_me:$LINENO: error: Please activate the extended I-pipe support in $RTAI_LINUX_DIR and rebuild your kernel" >&5
+echo "$as_me: error: Please activate the extended I-pipe support in $RTAI_LINUX_DIR and rebuild your kernel" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+   if test x${CONFIG_IPIPE_EXTENDED} = x; then
+      { { echo "$as_me:$LINENO: error: Please re-patch your kernel with the extended I-pipe support" >&5
+echo "$as_me: error: Please re-patch your kernel with the extended I-pipe support" >&2;}
    { (exit 1); exit 1; }; }
    fi
 elif test -r $RTAI_LINUX_SRCDIR/include/linux/adeos.h; then
@@ -22122,11 +22131,11 @@ fi
 
 RTAI_MODULE_EXT=.ko
 RTAI_KBUILD_ENV='src2obj = $(patsubst %.$(1),%.o,$(filter %.$(1),$(call notdir,$(2))))'
-RTAI_KBUILD_TOP="@if test -e $RTAI_LINUX_DIR/Module.symvers; then mv -f $RTAI_LINUX_DIR/Module.symvers $RTAI_LINUX_DIR/__Module.symvers; fi; if test -e $RTAI_LINUX_DIR/vmlinux; then mv -f $RTAI_LINUX_DIR/vmlinux $RTAI_LINUX_DIR/__vmlinux; fi; "
-RTAI_KBUILD_BOTTOM="&& if test -e $RTAI_LINUX_DIR/__Module.symvers; then mv -f $RTAI_LINUX_DIR/__Module.symvers $RTAI_LINUX_DIR/Module.symvers; fi && if test -e $RTAI_LINUX_DIR/__vmlinux; then mv -f $RTAI_LINUX_DIR/__vmlinux $RTAI_LINUX_DIR/vmlinux; fi"
+RTAI_KBUILD_TOP=@
+RTAI_KBUILD_BOTTOM=
 RTAI_KBUILD_CMD="for src in \$(filter-out FORCE, \$^); do if test \\! -r \`basename \$\$src\`; then \$(LN_S) \$\$src; fi; done; \
                     \$(MAKE) -C $RTAI_LINUX_DIR CROSS_COMPILE=\$(CROSS_COMPILE) CC=$CC ARCH=$RTAI_TARGET_ARCH \
-		    M=\$\$PWD rtai_srctree=\`cd \$(top_srcdir) && pwd\` rtai_srcdir=\`cd \$(srcdir) && pwd\` V=\$(V) modules \
+		    M=\$\$PWD rtai_srctree=\`cd \$(top_srcdir) && pwd\` rtai_srcdir=\`cd \$(srcdir) && pwd\` V=\$(V) MODVERDIR=$top_builddir/symbols modules \
 		    rtai_objs='\$(call src2obj,c,\$^) \$(call src2obj,S,\$^) \$(call src2obj,cc,\$^) \$(call src2obj,cpp,\$^)' rtai_target=\$(basename \$@)"
 
 RTAI_KBUILD_CLEAN='rm -f *.ko *.mod.c .*.cmd *.o'
@@ -22301,6 +22310,7 @@ fi
           ac_config_links="$ac_config_links testsuite/klatency/Makefile:testsuite/klatency/Makefile.kbuild"
 
           ac_config_links="$ac_config_links drivers/16550A/Makefile:drivers/16550A/Makefile.kbuild"
+
 
 
 
@@ -23545,6 +23555,7 @@ s,@RTAI_LINUX_DIR@,$RTAI_LINUX_DIR,;t t
 s,@RTAI_LINUX_VERSION@,$RTAI_LINUX_VERSION,;t t
 s,@RTAI_MODULE_DIR@,$RTAI_MODULE_DIR,;t t
 s,@RTAI_MODULE_EXT@,$RTAI_MODULE_EXT,;t t
+s,@RTAI_SYMBOL_DIR@,$RTAI_SYMBOL_DIR,;t t
 s,@RTAI_KBUILD_ENV@,$RTAI_KBUILD_ENV,;t t
 s,@RTAI_KBUILD_TOP@,$RTAI_KBUILD_TOP,;t t
 s,@RTAI_KBUILD_BOTTOM@,$RTAI_KBUILD_BOTTOM,;t t
