Add message queue support -- again

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CONFIG_RTAI_OPT_TRACES_TRUE CONFIG_RTAI_OPT_TRACES_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_ARCH_TUNE_FLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN CONFIG_RTAI_LINUXDIR subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CONFIG_RTAI_OPT_TRACES_TRUE CONFIG_RTAI_OPT_TRACES_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_ARCH_TUNE_FLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN CONFIG_RTAI_LINUXDIR subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1023,14 +1023,15 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
  --enable-posix-skin	Build POSIX skin
  --enable-rtai-skin	Build RTAI skin
- --enable-native-registry	Enable registry support for native skin
+ --enable-native-registry	Enable registry support in native skin
  --enable-native-registry-slots	Set maximum number of registry slots
- --enable-native-pipe	Enable pipe support for native skin
+ --enable-native-pipe	Enable pipe support in native skin
  --enable-native-pipe-bufsz	Set size of pipe fill space
- --enable-native-sem	Enable semaphore support for native skin
- --enable-native-event	Enable event flag support for native skin
- --enable-native-mutex	Enable mutex support for native skin
- --enable-native-cond	Enable condition variable support for native skin
+ --enable-native-sem	Enable semaphore support in native skin
+ --enable-native-event	Enable event flag support in native skin
+ --enable-native-mutex	Enable mutex support in native skin
+ --enable-native-cond	Enable condition variable support in native skin
+ --enable-native-queue	Enable message queue support in native skin
  --enable-psos-skin	Build pSOS+ emulator
  --enable-vxworks-skin	Build VxWorks emulator
  --enable-vrtx-skin	Build VRTX emulator
@@ -4702,7 +4703,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4705 "configure"' > conftest.$ac_ext
+  echo '#line 4706 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5231,7 +5232,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5234: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5235: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7063,7 +7064,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7066 "configure"
+#line 7067 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7161,7 +7162,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7164 "configure"
+#line 7165 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8529,6 +8530,19 @@ fi;
 echo "$as_me:$LINENO: result: ${CONFIG_RTAI_OPT_NATIVE_COND:-no}" >&5
 echo "${ECHO_T}${CONFIG_RTAI_OPT_NATIVE_COND:-no}" >&6
 
+echo "$as_me:$LINENO: checking for native message queue support" >&5
+echo $ECHO_N "checking for native message queue support... $ECHO_C" >&6
+# Check whether --enable-native-queue or --disable-native-queue was given.
+if test "${enable_native_queue+set}" = set; then
+  enableval="$enable_native_queue"
+  case "$enableval" in
+	y | yes) CONFIG_RTAI_OPT_NATIVE_QUEUE=y ;;
+	*) unset CONFIG_RTAI_OPT_NATIVE_QUEUE ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTAI_OPT_NATIVE_QUEUE:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTAI_OPT_NATIVE_QUEUE:-no}" >&6
+
 echo "$as_me:$LINENO: checking for pSOS+ skin" >&5
 echo $ECHO_N "checking for pSOS+ skin... $ECHO_C" >&6
 # Check whether --enable-psos-skin or --disable-psos-skin was given.
@@ -9340,6 +9354,11 @@ cat >>confdefs.h <<\_ACEOF
 #define CONFIG_RTAI_OPT_NATIVE_COND 1
 _ACEOF
 
+test \! x$CONFIG_RTAI_OPT_NATIVE_QUEUE = x &&
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTAI_OPT_NATIVE_QUEUE 1
+_ACEOF
+
 
 
 
@@ -9523,6 +9542,16 @@ if test x$CONFIG_RTAI_OPT_NATIVE_COND = xy; then
 else
   CONFIG_RTAI_OPT_NATIVE_COND_TRUE='#'
   CONFIG_RTAI_OPT_NATIVE_COND_FALSE=
+fi
+
+
+
+if test x$CONFIG_RTAI_OPT_NATIVE_QUEUE = xy; then
+  CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE=
+  CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE='#'
+else
+  CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE='#'
+  CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE=
 fi
 
 
@@ -9966,6 +9995,13 @@ if test -z "${CONFIG_RTAI_OPT_NATIVE_COND_TRUE}" && test -z "${CONFIG_RTAI_OPT_N
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_OPT_NATIVE_COND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTAI_OPT_NATIVE_COND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE}" && test -z "${CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_OPT_NATIVE_QUEUE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTAI_OPT_NATIVE_QUEUE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10707,6 +10743,8 @@ s,@CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE@,$CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE,;t t
 s,@CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE@,$CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE,;t t
 s,@CONFIG_RTAI_OPT_NATIVE_COND_TRUE@,$CONFIG_RTAI_OPT_NATIVE_COND_TRUE,;t t
 s,@CONFIG_RTAI_OPT_NATIVE_COND_FALSE@,$CONFIG_RTAI_OPT_NATIVE_COND_FALSE,;t t
+s,@CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE@,$CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE,;t t
+s,@CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE@,$CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE,;t t
 s,@CONFIG_RTAI_DOC_DOX_TRUE@,$CONFIG_RTAI_DOC_DOX_TRUE,;t t
 s,@CONFIG_RTAI_DOC_DOX_FALSE@,$CONFIG_RTAI_DOC_DOX_FALSE,;t t
 s,@CONFIG_RTAI_MAINT_TRUE@,$CONFIG_RTAI_MAINT_TRUE,;t t
