Fix compilation

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_PMA_TRUE CONFIG_RTAI_MAINT_PMA_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_VM_TRUE CONFIG_RTAI_OPT_VM_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -9323,6 +9323,17 @@ fi
 
 
 
+if test "$CONFIG_RTAI_HW_FPU" = y; then
+  CONFIG_RTAI_HW_FPU_TRUE=
+  CONFIG_RTAI_HW_FPU_FALSE='#'
+else
+  CONFIG_RTAI_HW_FPU_TRUE='#'
+  CONFIG_RTAI_HW_FPU_FALSE=
+fi
+
+
+
+
 if test x$CONFIG_RTAI_SKIN_POSIX = xy; then
   CONFIG_RTAI_SKIN_POSIX_TRUE=
   CONFIG_RTAI_SKIN_POSIX_FALSE='#'
@@ -9476,12 +9487,12 @@ fi
 
 
 
-if test "$CONFIG_RTAI_MAINT_PMA" = y; then
-  CONFIG_RTAI_MAINT_PMA_TRUE=
-  CONFIG_RTAI_MAINT_PMA_FALSE='#'
+if test "$CONFIG_RTAI_MAINT_GCH" = y; then
+  CONFIG_RTAI_MAINT_GCH_TRUE=
+  CONFIG_RTAI_MAINT_GCH_FALSE='#'
 else
-  CONFIG_RTAI_MAINT_PMA_TRUE='#'
-  CONFIG_RTAI_MAINT_PMA_FALSE=
+  CONFIG_RTAI_MAINT_GCH_TRUE='#'
+  CONFIG_RTAI_MAINT_GCH_FALSE=
 fi
 
 
@@ -9780,6 +9791,13 @@ echo "$as_me: error: conditional \"CONFIG_SMP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RTAI_HW_FPU_TRUE}" && test -z "${CONFIG_RTAI_HW_FPU_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_HW_FPU\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTAI_HW_FPU\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RTAI_SKIN_POSIX_TRUE}" && test -z "${CONFIG_RTAI_SKIN_POSIX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_SKIN_POSIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -9885,10 +9903,10 @@ echo "$as_me: error: conditional \"CONFIG_RTAI_MAINT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${CONFIG_RTAI_MAINT_PMA_TRUE}" && test -z "${CONFIG_RTAI_MAINT_PMA_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_MAINT_PMA\" was never defined.
+if test -z "${CONFIG_RTAI_MAINT_GCH_TRUE}" && test -z "${CONFIG_RTAI_MAINT_GCH_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTAI_MAINT_GCH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"CONFIG_RTAI_MAINT_PMA\" was never defined.
+echo "$as_me: error: conditional \"CONFIG_RTAI_MAINT_GCH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10572,6 +10590,8 @@ s,@CONFIG_PPC_TRUE@,$CONFIG_PPC_TRUE,;t t
 s,@CONFIG_PPC_FALSE@,$CONFIG_PPC_FALSE,;t t
 s,@CONFIG_SMP_TRUE@,$CONFIG_SMP_TRUE,;t t
 s,@CONFIG_SMP_FALSE@,$CONFIG_SMP_FALSE,;t t
+s,@CONFIG_RTAI_HW_FPU_TRUE@,$CONFIG_RTAI_HW_FPU_TRUE,;t t
+s,@CONFIG_RTAI_HW_FPU_FALSE@,$CONFIG_RTAI_HW_FPU_FALSE,;t t
 s,@CONFIG_RTAI_SKIN_POSIX_TRUE@,$CONFIG_RTAI_SKIN_POSIX_TRUE,;t t
 s,@CONFIG_RTAI_SKIN_POSIX_FALSE@,$CONFIG_RTAI_SKIN_POSIX_FALSE,;t t
 s,@CONFIG_RTAI_SKIN_NATIVE_TRUE@,$CONFIG_RTAI_SKIN_NATIVE_TRUE,;t t
@@ -10602,8 +10622,8 @@ s,@CONFIG_RTAI_DOC_DOX_TRUE@,$CONFIG_RTAI_DOC_DOX_TRUE,;t t
 s,@CONFIG_RTAI_DOC_DOX_FALSE@,$CONFIG_RTAI_DOC_DOX_FALSE,;t t
 s,@CONFIG_RTAI_MAINT_TRUE@,$CONFIG_RTAI_MAINT_TRUE,;t t
 s,@CONFIG_RTAI_MAINT_FALSE@,$CONFIG_RTAI_MAINT_FALSE,;t t
-s,@CONFIG_RTAI_MAINT_PMA_TRUE@,$CONFIG_RTAI_MAINT_PMA_TRUE,;t t
-s,@CONFIG_RTAI_MAINT_PMA_FALSE@,$CONFIG_RTAI_MAINT_PMA_FALSE,;t t
+s,@CONFIG_RTAI_MAINT_GCH_TRUE@,$CONFIG_RTAI_MAINT_GCH_TRUE,;t t
+s,@CONFIG_RTAI_MAINT_GCH_FALSE@,$CONFIG_RTAI_MAINT_GCH_FALSE,;t t
 s,@CONFIG_RTAI_MAINT_PGM_TRUE@,$CONFIG_RTAI_MAINT_PGM_TRUE,;t t
 s,@CONFIG_RTAI_MAINT_PGM_FALSE@,$CONFIG_RTAI_MAINT_PGM_FALSE,;t t
 s,@CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE@,$CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE,;t t
