Merge the ppc64 port

diff --git a/fusion/configure b/fusion/configure
--- a/fusion/configure
+++ b/fusion/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all sim"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT CONFIG_RTAI_HW_SMI_DETECT_TRUE CONFIG_RTAI_HW_SMI_DETECT_FALSE RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_IA64_TRUE CONFIG_IA64_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_LTT_TRUE CONFIG_LTT_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_OPT_FUSION_TRUE CONFIG_RTAI_OPT_FUSION_FALSE CONFIG_RTAI_OPT_PIPE_TRUE CONFIG_RTAI_OPT_PIPE_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_UVM_TRUE CONFIG_RTAI_OPT_UVM_FALSE CONFIG_RTAI_DRIVERS_16550A_TRUE CONFIG_RTAI_DRIVERS_16550A_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE CONFIG_RTAI_OPT_NATIVE_HEAP_TRUE CONFIG_RTAI_OPT_NATIVE_HEAP_FALSE CONFIG_RTAI_OPT_NATIVE_ALARM_TRUE CONFIG_RTAI_OPT_NATIVE_ALARM_FALSE CONFIG_RTAI_OPT_NATIVE_INTR_TRUE CONFIG_RTAI_OPT_NATIVE_INTR_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN RTAI_PIPE_NRDEV subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT CONFIG_RTAI_HW_SMI_DETECT_TRUE CONFIG_RTAI_HW_SMI_DETECT_FALSE RTAI_MAYBE_SIMDIR RTAI_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_X86_LOCAL_APIC_TRUE CONFIG_X86_LOCAL_APIC_FALSE CONFIG_X86_TRUE CONFIG_X86_FALSE CONFIG_PPC_TRUE CONFIG_PPC_FALSE CONFIG_PPC64_TRUE CONFIG_PPC64_FALSE CONFIG_IA64_TRUE CONFIG_IA64_FALSE CONFIG_SMP_TRUE CONFIG_SMP_FALSE CONFIG_LTT_TRUE CONFIG_LTT_FALSE CONFIG_RTAI_HW_FPU_TRUE CONFIG_RTAI_HW_FPU_FALSE CONFIG_RTAI_OPT_FUSION_TRUE CONFIG_RTAI_OPT_FUSION_FALSE CONFIG_RTAI_OPT_PIPE_TRUE CONFIG_RTAI_OPT_PIPE_FALSE CONFIG_RTAI_SKIN_POSIX_TRUE CONFIG_RTAI_SKIN_POSIX_FALSE CONFIG_RTAI_SKIN_NATIVE_TRUE CONFIG_RTAI_SKIN_NATIVE_FALSE CONFIG_RTAI_SKIN_PSOS_TRUE CONFIG_RTAI_SKIN_PSOS_FALSE CONFIG_RTAI_SKIN_VXWORKS_TRUE CONFIG_RTAI_SKIN_VXWORKS_FALSE CONFIG_RTAI_SKIN_VRTX_TRUE CONFIG_RTAI_SKIN_VRTX_FALSE CONFIG_RTAI_SKIN_UITRON_TRUE CONFIG_RTAI_SKIN_UITRON_FALSE CONFIG_RTAI_OPT_UVM_TRUE CONFIG_RTAI_OPT_UVM_FALSE CONFIG_RTAI_DRIVERS_16550A_TRUE CONFIG_RTAI_DRIVERS_16550A_FALSE CONFIG_RTAI_OPT_NATIVE_REGISTRY_TRUE CONFIG_RTAI_OPT_NATIVE_REGISTRY_FALSE CONFIG_RTAI_OPT_NATIVE_PIPE_TRUE CONFIG_RTAI_OPT_NATIVE_PIPE_FALSE CONFIG_RTAI_OPT_NATIVE_SEM_TRUE CONFIG_RTAI_OPT_NATIVE_SEM_FALSE CONFIG_RTAI_OPT_NATIVE_EVENT_TRUE CONFIG_RTAI_OPT_NATIVE_EVENT_FALSE CONFIG_RTAI_OPT_NATIVE_MUTEX_TRUE CONFIG_RTAI_OPT_NATIVE_MUTEX_FALSE CONFIG_RTAI_OPT_NATIVE_COND_TRUE CONFIG_RTAI_OPT_NATIVE_COND_FALSE CONFIG_RTAI_OPT_NATIVE_QUEUE_TRUE CONFIG_RTAI_OPT_NATIVE_QUEUE_FALSE CONFIG_RTAI_OPT_NATIVE_HEAP_TRUE CONFIG_RTAI_OPT_NATIVE_HEAP_FALSE CONFIG_RTAI_OPT_NATIVE_ALARM_TRUE CONFIG_RTAI_OPT_NATIVE_ALARM_FALSE CONFIG_RTAI_OPT_NATIVE_INTR_TRUE CONFIG_RTAI_OPT_NATIVE_INTR_FALSE CONFIG_RTAI_DOC_DOX_TRUE CONFIG_RTAI_DOC_DOX_FALSE CONFIG_RTAI_MAINT_TRUE CONFIG_RTAI_MAINT_FALSE CONFIG_RTAI_MAINT_GCH_TRUE CONFIG_RTAI_MAINT_GCH_FALSE CONFIG_RTAI_MAINT_PGM_TRUE CONFIG_RTAI_MAINT_PGM_FALSE CONFIG_RTAI_OLD_FASHIONED_BUILD_TRUE CONFIG_RTAI_OLD_FASHIONED_BUILD_FALSE CROSS_COMPILE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE RTAI_BUILD_STRING RTAI_HOST_STRING RTAI_TARGET_ARCH RTAI_TARGET_SUBARCH RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_KMOD_APP_CFLAGS RTAI_USER_APP_CFLAGS RTAI_FP_CFLAGS RTAI_LINUX_DIR RTAI_LINUX_VERSION RTAI_MODULE_DIR RTAI_MODULE_EXT RTAI_KBUILD_ENV RTAI_KBUILD_TOP RTAI_KBUILD_BOTTOM RTAI_KBUILD_CMD RTAI_KBUILD_CLEAN RTAI_KBUILD_DISTCLEAN RTAI_PIPE_NRDEV subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19575,6 +19575,11 @@ case "$host" in
 	wanted_kernel_arch=CONFIG_PPC
 	arch_have_sim=y
         ;;
+ powerpc64-*|ppc64-*)
+	RTAI_TARGET_ARCH=ppc64
+	wanted_kernel_arch=CONFIG_PPC64
+	arch_have_sim=y
+        ;;
  ia64-*)
 	RTAI_TARGET_ARCH=ia64
 	wanted_kernel_arch=CONFIG_IA64
@@ -20349,7 +20354,7 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
         ;;
- ppc)
+ ppc|ppc64)
 	timer_type=decrementer
         ;;
  ia64)
@@ -21618,6 +21623,16 @@ fi
 
 
 
+if test "$CONFIG_PPC64" = y; then
+  CONFIG_PPC64_TRUE=
+  CONFIG_PPC64_FALSE='#'
+else
+  CONFIG_PPC64_TRUE='#'
+  CONFIG_PPC64_FALSE=
+fi
+
+
+
 if test "$CONFIG_IA64" = y; then
   CONFIG_IA64_TRUE=
   CONFIG_IA64_FALSE='#'
@@ -22036,6 +22051,11 @@ case $RTAI_TARGET_ARCH in
 	RTAI_USER_CFLAGS="$RTAI_USER_CFLAGS -Wall -pipe"
 	RTAI_FP_CFLAGS="-ffast-math -mhard-float"
         ;;
+ ppc64)
+	RTAI_TARGET_SUBARCH=
+	RTAI_USER_CFLAGS="$RTAI_USER_CFLAGS -Wall -Wstrict-prototypes -pipe"
+	RTAI_FP_CFLAGS="-ffast-math -mhard-float"
+        ;;
  ia64)
 	RTAI_TARGET_SUBARCH=
 	RTAI_USER_CFLAGS="$RTAI_USER_CFLAGS -Wall -pipe"
@@ -22123,7 +22143,7 @@ fi
 
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile arch/GNUmakefile arch/i386/GNUmakefile arch/i386/hal/GNUmakefile arch/ppc/GNUmakefile arch/ppc/hal/GNUmakefile arch/ia64/GNUmakefile arch/ia64/hal/GNUmakefile include/GNUmakefile include/nucleus/GNUmakefile include/nucleus/asm-generic/GNUmakefile include/nucleus/asm-i386/GNUmakefile include/nucleus/asm-ppc/GNUmakefile include/nucleus/asm-ia64/GNUmakefile include/nucleus/asm-uvm/GNUmakefile nucleus/GNUmakefile scripts/GNUmakefile scripts/rtai-config scripts/rtai-load scripts/rtai-test testsuite/GNUmakefile testsuite/latency/GNUmakefile testsuite/klatency/GNUmakefile testsuite/cruncher/GNUmakefile testsuite/switch/GNUmakefile skins/GNUmakefile skins/uvm/GNUmakefile skins/uvm/lib/GNUmakefile skins/posix/GNUmakefile skins/posix/lib/GNUmakefile skins/rtai/GNUmakefile skins/rtai/lib/GNUmakefile skins/psos+/GNUmakefile skins/uitron/GNUmakefile skins/vrtx/GNUmakefile skins/vxworks/GNUmakefile drivers/GNUmakefile drivers/16550A/GNUmakefile drivers/16550A/lib/GNUmakefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile arch/GNUmakefile arch/i386/GNUmakefile arch/i386/hal/GNUmakefile arch/ppc/GNUmakefile arch/ppc/hal/GNUmakefile arch/ppc64/GNUmakefile arch/ppc64/hal/GNUmakefile arch/ia64/GNUmakefile arch/ia64/hal/GNUmakefile include/GNUmakefile include/nucleus/GNUmakefile include/nucleus/asm-generic/GNUmakefile include/nucleus/asm-i386/GNUmakefile include/nucleus/asm-ppc/GNUmakefile include/nucleus/asm-ppc64/GNUmakefile include/nucleus/asm-ia64/GNUmakefile include/nucleus/asm-uvm/GNUmakefile nucleus/GNUmakefile scripts/GNUmakefile scripts/rtai-config scripts/rtai-load scripts/rtai-test testsuite/GNUmakefile testsuite/latency/GNUmakefile testsuite/klatency/GNUmakefile testsuite/cruncher/GNUmakefile testsuite/switch/GNUmakefile skins/GNUmakefile skins/uvm/GNUmakefile skins/uvm/lib/GNUmakefile skins/posix/GNUmakefile skins/posix/lib/GNUmakefile skins/rtai/GNUmakefile skins/rtai/lib/GNUmakefile skins/psos+/GNUmakefile skins/uitron/GNUmakefile skins/vrtx/GNUmakefile skins/vxworks/GNUmakefile drivers/GNUmakefile drivers/16550A/GNUmakefile drivers/16550A/lib/GNUmakefile"
 
 
 if test \! x$RTAI_MAYBE_DOCDIR = x; then
@@ -22296,6 +22316,13 @@ if test -z "${CONFIG_PPC_TRUE}" && test -z "${CONFIG_PPC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_PPC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_PPC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_PPC64_TRUE}" && test -z "${CONFIG_PPC64_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_PPC64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_PPC64\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22956,6 +22983,8 @@ do
   "arch/i386/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/i386/hal/GNUmakefile" ;;
   "arch/ppc/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ppc/GNUmakefile" ;;
   "arch/ppc/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ppc/hal/GNUmakefile" ;;
+  "arch/ppc64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ppc64/GNUmakefile" ;;
+  "arch/ppc64/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ppc64/hal/GNUmakefile" ;;
   "arch/ia64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ia64/GNUmakefile" ;;
   "arch/ia64/hal/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES arch/ia64/hal/GNUmakefile" ;;
   "include/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/GNUmakefile" ;;
@@ -22963,6 +22992,7 @@ do
   "include/nucleus/asm-generic/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-generic/GNUmakefile" ;;
   "include/nucleus/asm-i386/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-i386/GNUmakefile" ;;
   "include/nucleus/asm-ppc/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-ppc/GNUmakefile" ;;
+  "include/nucleus/asm-ppc64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-ppc64/GNUmakefile" ;;
   "include/nucleus/asm-ia64/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-ia64/GNUmakefile" ;;
   "include/nucleus/asm-uvm/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES include/nucleus/asm-uvm/GNUmakefile" ;;
   "nucleus/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES nucleus/GNUmakefile" ;;
@@ -23199,6 +23229,8 @@ s,@CONFIG_X86_TRUE@,$CONFIG_X86_TRUE,;t t
 s,@CONFIG_X86_FALSE@,$CONFIG_X86_FALSE,;t t
 s,@CONFIG_PPC_TRUE@,$CONFIG_PPC_TRUE,;t t
 s,@CONFIG_PPC_FALSE@,$CONFIG_PPC_FALSE,;t t
+s,@CONFIG_PPC64_TRUE@,$CONFIG_PPC64_TRUE,;t t
+s,@CONFIG_PPC64_FALSE@,$CONFIG_PPC64_FALSE,;t t
 s,@CONFIG_IA64_TRUE@,$CONFIG_IA64_TRUE,;t t
 s,@CONFIG_IA64_FALSE@,$CONFIG_IA64_FALSE,;t t
 s,@CONFIG_SMP_TRUE@,$CONFIG_SMP_TRUE,;t t
